package com.hbm_m.test;

import com.hbm_m.platform.PlatformHooks;

import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestAssertException;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
//? if forge {
import net.minecraftforge.gametest.GameTestHolder;
import net.minecraftforge.gametest.PrefixGameTestTemplate;
//?} elif neoforge {
/*import net.neoforged.neoforge.gametest.GameTestHolder;
import net.neoforged.neoforge.gametest.PrefixGameTestTemplate;
*///?}

/**
 * Parity suite: verifies that the OBSERVABLE contract of {@link PlatformHooks}
 * is identical on 1.20.1-forge and 1.21.1-neoforge.
 *
 * <p>The main multi-version risk is the difference between a <b>live reference</b>
 * (1.20.1 {@code stack.getTag()}) and a <b>copy</b> (1.21.1 {@code data.copyTag()}).
 * These tests pin invariants that <b>must</b> hold on both versions, thereby catching
 * regressions if anyone breaks the read-modify-write contract in {@code editItemTag}
 * or accidentally returns a live tag on 1.21.1.
 *
 * <p>Additionally, the "copy-does-not-persist" tests encode version-dependent
 * expectations via stonecutter gating — on 1.21.1 mutating the tag returned by
 * {@code getItemTag} must NOT persist, while on 1.20.1 it must (live reference).
 * This documents a key semantic difference, not a bug.
 *
 * <p>Structures are the mod's own empty templates {@code hbm_m:empty3x3x3} and
 * {@code hbm_m:empty5x5x5}, generated by the script
 * {@code scripts/gen_gametest_structures.py} into <b>both</b> folders
 * ({@code data/hbm_m/structures/} for 1.20.1 and {@code data/hbm_m/structure/}
 * for 1.21.1 — MC 1.21 renamed the structure resource directory). Both annotations
 * are FQN-gated (they differ between Forge/NeoForge):
 * {@code @GameTestHolder("hbm_m")} — (a) auto-registers the test methods
 * (so {@link GameTestRegistration} is optional but kept for explicitness)
 * and (b) sets {@code templateNamespace = "hbm_m"} for all {@code @GameTest}s;
 * {@code @PrefixGameTestTemplate(false)} disables auto-prefixing with the class name,
 * otherwise {@code template="empty3x3x3"} would become
 * {@code crossloaderparitygametest.empty3x3x3} and the template wouldn't be found.
 *
 * <p>Run: {@code ./gradlew :1.21.1-neoforge:runGameTestServer} and
 * {@code ./gradlew "Set active project to 1.20.1-forge" && ./gradlew :1.20.1-forge:runGameTestServer}.
 */
@GameTestHolder("hbm_m")
@PrefixGameTestTemplate(false)
public final class CrossLoaderParityGameTest {

    private CrossLoaderParityGameTest() {}

    private static void check(boolean cond, String msg) {
        if (!cond) throw new GameTestAssertException(msg);
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Parity 1: putLong → getLong round-trip. Identical on both versions.
    //  This is the basic invariant: regardless of whether the tag is a copy
    //  or a live reference, the typed getter must return the written value.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_putLongGetLong_positive(GameTestHelper helper) {
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putLong(stack, "energy", 1_000_000L);
        check(PlatformHooks.getLong(stack, "energy") == 1_000_000L,
                "putLong/getLong round-trip must hold on both versions");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_putLongGetLong_zero(GameTestHelper helper) {
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putLong(stack, "energy", 0L);
        check(PlatformHooks.getLong(stack, "energy") == 0L,
                "putLong(0) must round-trip on both versions");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_putLongGetLong_maxLong(GameTestHelper helper) {
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putLong(stack, "energy", Long.MAX_VALUE);
        check(PlatformHooks.getLong(stack, "energy") == Long.MAX_VALUE,
                "putLong(Long.MAX_VALUE) must round-trip on both versions");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_putLongGetLong_negative(GameTestHelper helper) {
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putLong(stack, "debt", -500L);
        check(PlatformHooks.getLong(stack, "debt") == -500L,
                "putLong(negative) must round-trip on both versions");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Parity 2: putInt → getInt round-trip.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_putIntGetInt_roundTrip(GameTestHelper helper) {
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putInt(stack, "count", 42);
        check(PlatformHooks.getInt(stack, "count") == 42,
                "putInt/getInt round-trip must hold on both versions");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Parity 3: putBoolean → getBoolean round-trip (both values).
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_putBooleanGetBoolean_true(GameTestHelper helper) {
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putBoolean(stack, "active", true);
        check(PlatformHooks.getBoolean(stack, "active"),
                "putBoolean(true)/getBoolean must round-trip on both versions");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_putBooleanGetBoolean_false(GameTestHelper helper) {
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putBoolean(stack, "active", false);
        check(!PlatformHooks.getBoolean(stack, "active"),
                "putBoolean(false)/getBoolean must round-trip on both versions");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Parity 4: putString → getString round-trip (including UTF-8 — the project requires UTF-8).
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_putStringGetString_ascii(GameTestHelper helper) {
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putString(stack, "label", "reactor_core");
        check("reactor_core".equals(PlatformHooks.getString(stack, "label")),
                "putString/getString ASCII must round-trip on both versions");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_putStringGetString_utf8(GameTestHelper helper) {
        // The project requires UTF-8 (see java-coding-standards, build.*.gradle.kts).
        // Non-ASCII characters are a common case in tooltips and names.
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putString(stack, "ru", "Réacteur");
        check("Réacteur".equals(PlatformHooks.getString(stack, "ru")),
                "putString/getString UTF-8 must round-trip on both versions");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Parity 5: editItemTag — read-modify-write must NOT lose sibling keys.
    //  This is a critical invariant: on 1.21.1 every editItemTag copies → edits → sets,
    //  so keys are easily lost if the editor works with an empty tag.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_editItemTag_preservesAllKeys(GameTestHelper helper) {
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putLong(stack, "energy", 100L);
        PlatformHooks.putInt(stack, "tier", 2);
        PlatformHooks.putString(stack, "name", "core");
        PlatformHooks.putBoolean(stack, "active", true);
        // Now a single modification via editItemTag.
        PlatformHooks.editItemTag(stack, t -> t.putLong("energy", t.getLong("energy") + 50L));
        // All keys must survive + energy must be incremented.
        check(PlatformHooks.getLong(stack, "energy") == 150L, "edited key must update");
        check(PlatformHooks.getInt(stack, "tier") == 2, "unrelated int key must persist");
        check("core".equals(PlatformHooks.getString(stack, "name")), "unrelated string key must persist");
        check(PlatformHooks.getBoolean(stack, "active"), "unrelated boolean key must persist");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Parity 6: setItemTag(null) → getItemTag(null) — clearing contract.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_setNullClears_tagBecomesNull(GameTestHelper helper) {
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putLong(stack, "energy", 100L);
        check(PlatformHooks.getItemTag(stack) != null, "precondition: tag present");
        PlatformHooks.setItemTag(stack, null);
        check(PlatformHooks.getItemTag(stack) == null,
                "after setItemTag(null), getItemTag must be null on both versions");
        check(!PlatformHooks.hasItemTag(stack),
                "after setItemTag(null), hasItemTag must be false on both versions");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Parity 7: contains — key presence/absence.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_contains_afterPut_true(GameTestHelper helper) {
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putLong(stack, "energy", 1L);
        check(PlatformHooks.contains(stack, "energy"),
                "contains must be true for existing key on both versions");
        check(!PlatformHooks.contains(stack, "missing"),
                "contains must be false for missing key on both versions");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Parity 8: remove — deletes one key, keeps the rest.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_remove_isolatesKey(GameTestHelper helper) {
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putLong(stack, "a", 1L);
        PlatformHooks.putLong(stack, "b", 2L);
        PlatformHooks.putLong(stack, "c", 3L);
        PlatformHooks.remove(stack, "b");
        check(!PlatformHooks.contains(stack, "b"), "removed key must be gone");
        check(PlatformHooks.contains(stack, "a"), "sibling a must persist");
        check(PlatformHooks.contains(stack, "c"), "sibling c must persist");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Parity 9: save/load of ItemStack with NBT — round-trip preserves custom NBT.
    //  CRITICAL: on 1.21.1 the NBT is stored in the CUSTOM_DATA DataComponent.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_saveLoad_preservesCustomNbt(GameTestHelper helper) {
        var provider = helper.getLevel().registryAccess();
        ItemStack original = new ItemStack(Items.DIAMOND);
        PlatformHooks.putLong(original, "energy", 4242L);
        PlatformHooks.putString(original, "serial", "RX-001");
        PlatformHooks.putInt(original, "tier", 5);

        CompoundTag saved = PlatformHooks.safeItemSave(original, provider);
        ItemStack loaded = PlatformHooks.itemStackOf(saved, provider);

        check(loaded.getItem() == Items.DIAMOND, "item type must survive save/load");
        check(PlatformHooks.getLong(loaded, "energy") == 4242L, "custom long must survive save/load");
        check("RX-001".equals(PlatformHooks.getString(loaded, "serial")), "custom string must survive save/load");
        check(PlatformHooks.getInt(loaded, "tier") == 5, "custom int must survive save/load");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_saveLoad_preservesCount(GameTestHelper helper) {
        var provider = helper.getLevel().registryAccess();
        ItemStack original = new ItemStack(Items.IRON_INGOT, 64);
        CompoundTag saved = PlatformHooks.safeItemSave(original, provider);
        ItemStack loaded = PlatformHooks.itemStackOf(saved, provider);
        check(loaded.getCount() == 64, "stack count must survive save/load on both versions");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Parity 10: isSameItemSameTags — equivalence after save/load.
    //  If the round-trip passes, the original and the loaded stack must be "the same".
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_saveLoad_isSameItemSameTags(GameTestHelper helper) {
        var provider = helper.getLevel().registryAccess();
        ItemStack original = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putLong(original, "energy", 777L);
        CompoundTag saved = PlatformHooks.safeItemSave(original, provider);
        ItemStack loaded = PlatformHooks.itemStackOf(saved, provider);
        check(PlatformHooks.isSameItemSameTags(original, loaded),
                "save/load round-trip must yield isSameItemSameTags == true on both versions");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Documentation of a semantic difference (NOT parity, but a pinned contract):
    //
    //  On 1.20.1 getItemTag() returns a LIVE reference — mutations persist.
    //  On 1.21.1 getItemTag() returns a COPY — mutations do NOT persist.
    //
    //  These tests must NOT fail — they pin DIFFERENT expectations per version,
    //  thereby documenting why editItemTag is the only safe way to mutate on
    //  both versions.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void semantic_getItemTagMutation(GameTestHelper helper) {
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putLong(stack, "energy", 100L);
        CompoundTag tag = PlatformHooks.getItemTag(stack);
        check(tag != null, "precondition: tag present");
        // Mutate the returned tag directly (NOT via editItemTag).
        tag.putLong("energy", 999L);
        //? if < 1.21.1 {
        // 1.20.1: live reference — the mutation persists.
        check(PlatformHooks.getLong(stack, "energy") == 999L,
                "1.20.1: getItemTag returns live reference, mutation must persist");
        //?} else {
    /*// 1.21.1: copy — the mutation does NOT persist. The value stayed 100.
        check(PlatformHooks.getLong(stack, "energy") == 100L,
                "1.21.1: getItemTag returns copy, direct mutation must NOT persist (use editItemTag)");
        *///?}
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void semantic_editItemTag_alwaysPersists(GameTestHelper helper) {
        // Unlike direct getItemTag, editItemTag MUST persist on both versions.
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putLong(stack, "energy", 100L);
        PlatformHooks.editItemTag(stack, t -> t.putLong("energy", 999L));
        check(PlatformHooks.getLong(stack, "energy") == 999L,
                "editItemTag must persist on BOTH versions (read-modify-write contract)");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Parity 11: ItemStack.EMPTY — edge case, must not crash.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_emptyStack_safeAccessors(GameTestHelper helper) {
        // All typed getters on an EMPTY stack must return defaults, not crash.
        check(PlatformHooks.getInt(ItemStack.EMPTY, "x") == 0, "EMPTY getInt default");
        check(PlatformHooks.getLong(ItemStack.EMPTY, "x") == 0L, "EMPTY getLong default");
        check(!PlatformHooks.getBoolean(ItemStack.EMPTY, "x"), "EMPTY getBoolean default");
        check("".equals(PlatformHooks.getString(ItemStack.EMPTY, "x")), "EMPTY getString default");
        check(!PlatformHooks.contains(ItemStack.EMPTY, "x"), "EMPTY contains false");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Parity 12: repeated overwrites of the same key — last value wins.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "parity", timeoutTicks = 100)
    public static void parity_overwriteKey_lastValueWins(GameTestHelper helper) {
        ItemStack stack = new ItemStack(Items.IRON_INGOT);
        PlatformHooks.putLong(stack, "energy", 1L);
        PlatformHooks.putLong(stack, "energy", 2L);
        PlatformHooks.putLong(stack, "energy", 3L);
        check(PlatformHooks.getLong(stack, "energy") == 3L,
                "last putLong for same key must win on both versions");
        helper.succeed();
    }
}
