package com.hbm_m.test;

import com.hbm_m.capability.ChunkRadiation;
import com.hbm_m.config.ModClothConfig;
import com.hbm_m.extprop.HbmLivingProps;
import com.hbm_m.handler.EntityEffectHandler;
import com.hbm_m.handler.HazmatRegistry;
import com.hbm_m.hazard.HazardData;
import com.hbm_m.hazard.HazardEntry;
import com.hbm_m.hazard.HazardRegistry;
import com.hbm_m.hazard.HazardSystem;
import com.hbm_m.interfaces.IChunkRadiation;
import com.hbm_m.item.ModItems;
import com.hbm_m.lib.RefStrings;
import com.hbm_m.network.ChunkRadiationDebugBatchPacket;
import com.hbm_m.network.ModPacketHandler;
import com.hbm_m.network.RadiationDataPacket;
import com.hbm_m.network.sounds.GeigerSoundPacket;
import com.hbm_m.radiation.ChunkRadiationHandlerSimple;
import com.hbm_m.radiation.ChunkRadiationManager;
import com.hbm_m.radiation.PlayerHandler;
import com.hbm_m.util.ContaminationUtil;
import com.hbm_m.util.ContaminationUtil.ContaminationType;
import com.hbm_m.util.ContaminationUtil.HazardType;

import java.util.HashMap;
import java.util.Map;

import dev.architectury.networking.NetworkManager;
import io.netty.buffer.ByteBufUtil;
import io.netty.buffer.Unpooled;

import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestAssertException;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.network.FriendlyByteBuf;
import net.minecraft.network.protocol.Packet;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.animal.Cow;
import net.minecraft.world.entity.animal.Pig;
import net.minecraft.world.entity.monster.Zombie;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.level.ChunkPos;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockState;
//? if forge {
import net.minecraftforge.gametest.GameTestHolder;
import net.minecraftforge.gametest.PrefixGameTestTemplate;
//?} elif neoforge {
/*import net.neoforged.neoforge.gametest.GameTestHolder;
import net.neoforged.neoforge.gametest.PrefixGameTestTemplate;
 *///?}

/**
 * Extensive cross-platform GameTest suite for the mod's radiation system.
 *
 * <p>Covers all aspects of the radiation mechanics:
 * <ul>
 *   <li>{@link ChunkRadiation} — capability/attachment storing a chunk's ambient radiation (clamping, copyFrom).</li>
 *   <li>{@link ChunkRadiationManager} — static wrappers (get/set/incrementRad), config-gating.</li>
 *   <li>{@link ChunkRadiationHandlerSimple} — get/set/increment/decrement, receiveChunkLoad, clearSystem.</li>
 *   <li>{@link PlayerHandler} — getPlayerRads/setPlayerRads, rounding, clamp, null-safety.</li>
 *   <li>{@link HbmLivingProps} — get/set/increment radiation, radEnv/radBuf, cap 2500, Player delegation.</li>
 *   <li>{@link ContaminationUtil} — contaminate, calculateRadiationMod, isRadImmune, enums.</li>
 *   <li>{@link HazmatRegistry} — getResistance(ItemStack/Player), initDefault.</li>
 *   <li>{@link HazardSystem} — getHazardLevelFromStack/State, getHazardsFromStack, cache, sellafite.</li>
 *   <li>{@link HazardRegistry} — RADIATION singleton identity.</li>
 *   <li>{@link HazardData}/{@link HazardEntry} — override, mutex, baseLevel, addMod.</li>
 *   <li>{@link EntityEffectHandler} — radBuf snap, kill threshold of 1000 RAD.</li>
 *   <li>{@link com.hbm_m.hazard.type.HazardTypeRadiation} — rad = level / 20F.</li>
 *   <li>Network: radiation S2C channels ({@code radiation_data}, {@code chunk_rad_debug_batch},
 *       {@code geiger_sound}) — payload registration, outbound buf→Packet conversion
 *       (the path used by {@code ModPacketHandler.sendToPlayer} before handing off to the connection),
 *       codec symmetry write→decode.</li>
 * </ul>
 *
 * <p>Tests use the mod's own empty templates {@code hbm_m:empty3x3x3} and
 * {@code hbm_m:empty5x5x5} (generated by {@code scripts/gen_gametest_structures.py}
 * into both folders — {@code data/hbm_m/structures/} and {@code data/hbm_m/structure/}).
 * Annotations are FQN-gated (Forge/NeoForge differ):
 * {@code @GameTestHolder("hbm_m")} — auto-registration + {@code templateNamespace = "hbm_m"};
 * {@code @PrefixGameTestTemplate(false)} — disables the automatic class-name prefix.
 *
 * <p>Run: {@code ./gradlew :1.21.1-neoforge:runGameTestServer} (and likewise for forge).
 */
@GameTestHolder("hbm_m")
@PrefixGameTestTemplate(false)
public final class RadiationGameTest {

    private RadiationGameTest() {}

    // ════════════════════════════════════════════════════════════════════════
    //  Helper assert methods.
    // ════════════════════════════════════════════════════════════════════════

    private static void check(boolean cond, String msg) {
        if (!cond) throw new GameTestAssertException(msg);
    }

    private static void checkEq(float expected, float actual, String msg) {
        if (Math.abs(expected - actual) > 1e-4f) {
            throw new GameTestAssertException(msg + " (expected=" + expected + ", actual=" + actual + ")");
        }
    }

    /**
     * Version-compatible creation of a mock player.
     * 1.20.1 (forge): {@code GameTestHelper.makeMockPlayer()} → Player.
     * 1.21.1 (neoforge): {@code GameTestHelper.makeMockPlayer(GameType)} → Player.
     */
    private static Player makePlayer(GameTestHelper helper) {
        //? if < 1.21.1 {
        return helper.makeMockPlayer();
        //?} else {
        /*return helper.makeMockPlayer(net.minecraft.world.level.GameType.SURVIVAL);
        *///?}
    }

    /**
     * Creates a Cow and places it at world coordinates given by helper.absolutePos.
     * ENTITY tests must place the entity INSIDE the structure (via absolutePos),
     * not at fixed world coordinates (1,1,1) — otherwise chunk radiation from previous
     * tests (manager_setGetRadiation) may leak in through handleRadiationFromChunk.
     */
    private static Cow makeCowAt(GameTestHelper helper) {
        BlockPos abs = helper.absolutePos(new BlockPos(1, 1, 1));
        Cow cow = EntityType.COW.create(helper.getLevel());
        check(cow != null, "Cow entity must be creatable");
        cow.moveTo(abs.getX() + 0.5, abs.getY(), abs.getZ() + 0.5);
        return cow;
    }

    private static Pig makePigAt(GameTestHelper helper) {
        BlockPos abs = helper.absolutePos(new BlockPos(1, 1, 1));
        Pig pig = EntityType.PIG.create(helper.getLevel());
        check(pig != null, "Pig entity must be creatable");
        pig.moveTo(abs.getX() + 0.5, abs.getY(), abs.getZ() + 0.5);
        return pig;
    }

    /** Creates a LivingEntity (Cow) without adding it to the world — for persistentData/contaminate tests. */
    private static Cow makeCow(Level level) {
        Cow cow = EntityType.COW.create(level);
        check(cow != null, "Cow entity must be creatable");
        cow.moveTo(1.0, 1.0, 1.0);
        return cow;
    }

    /** Creates a Pig for EntityEffectHandler tests (kill threshold). */
    private static Pig makePig(Level level) {
        Pig pig = EntityType.PIG.create(level);
        check(pig != null, "Pig entity must be creatable");
        pig.moveTo(1.0, 1.0, 1.0);
        return pig;
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 1: ChunkRadiation (IChunkRadiation impl) — clamping, copyFrom, default.
    //  MAX_RAD = ModClothConfig.get().maxRad = 100_000F (default).
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void chunkRadiation_defaultZero(GameTestHelper helper) {
        IChunkRadiation cap = new ChunkRadiation();
        checkEq(0.0f, cap.getAmbientRadiation(), "ambient radiation must default to 0");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void chunkRadiation_setGet(GameTestHelper helper) {
        IChunkRadiation cap = new ChunkRadiation();
        cap.setAmbientRadiation(42.5f);
        checkEq(42.5f, cap.getAmbientRadiation(), "set→get round-trip");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void chunkRadiation_clampHigh(GameTestHelper helper) {
        IChunkRadiation cap = new ChunkRadiation();
        float maxRad = ModClothConfig.get().maxRad;
        cap.setAmbientRadiation(maxRad + 50_000f);
        checkEq(maxRad, cap.getAmbientRadiation(), "ambient clamped to maxRad");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void chunkRadiation_clampNegative(GameTestHelper helper) {
        IChunkRadiation cap = new ChunkRadiation();
        cap.setAmbientRadiation(-100f);
        checkEq(0.0f, cap.getAmbientRadiation(), "negative radiation clamped to 0");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void chunkRadiation_copyFrom(GameTestHelper helper) {
        IChunkRadiation source = new ChunkRadiation();
        source.setAmbientRadiation(77.7f);
        IChunkRadiation dest = new ChunkRadiation();
        dest.copyFrom(source);
        checkEq(77.7f, dest.getAmbientRadiation(), "copyFrom copies ambient");
        checkEq(source.getAmbientRadiation(), dest.getAmbientRadiation(),
                "copyFrom: source == dest");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void chunkRadiation_zeroIsZero(GameTestHelper helper) {
        IChunkRadiation cap = new ChunkRadiation();
        cap.setAmbientRadiation(0f);
        checkEq(0.0f, cap.getAmbientRadiation(), "explicit 0 stays 0");
        cap.setAmbientRadiation(10f);
        cap.setAmbientRadiation(0f);
        checkEq(0.0f, cap.getAmbientRadiation(), "reset to 0 after a value");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 2: ChunkRadiationManager — static wrappers, config-gating.
    //  They delegate to ChunkRadiationHandlerSimple via getProxy().
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void manager_setGetRadiation(GameTestHelper helper) {
        BlockPos abs = helper.absolutePos(new BlockPos(2, 1, 2));
        Level level = helper.getLevel();
        ChunkRadiationManager.setRadiation(level, abs.getX(), abs.getY(), abs.getZ(), 50f);
        float rad = ChunkRadiationManager.getRadiation(level, abs.getX(), abs.getY(), abs.getZ());
        checkEq(50f, rad, "setRadiation→getRadiation round-trip via Manager");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void manager_incrementRad(GameTestHelper helper) {
        BlockPos abs = helper.absolutePos(new BlockPos(2, 1, 2));
        Level level = helper.getLevel();
        ChunkRadiationManager.setRadiation(level, abs.getX(), abs.getY(), abs.getZ(), 100f);
        ChunkRadiationManager.incrementRad(level, abs.getX(), abs.getY(), abs.getZ(), 50f);
        float rad = ChunkRadiationManager.getRadiation(level, abs.getX(), abs.getY(), abs.getZ());
        checkEq(150f, rad, "incrementRad adds to existing radiation");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void manager_defaultZero(GameTestHelper helper) {
        BlockPos abs = helper.absolutePos(new BlockPos(2, 1, 2));
        Level level = helper.getLevel();
        // IMPORTANT: the gameTestServer world is persistent between runs (run/ folder) —
        // residual radiation from neighboring tests or past sessions may settle
        // in this chunk (spread + attachment saving). We explicitly clear the chunk
        // so that what is verified is exactly the semantics "zero radiation reads as 0".
        // The "fresh object = 0" semantics are covered by chunkRadiation_defaultZero.
        ChunkRadiationManager.setRadiation(level, abs.getX(), abs.getY(), abs.getZ(), 0f);
        float rad = ChunkRadiationManager.getRadiation(level, abs.getX(), abs.getY(), abs.getZ());
        checkEq(0f, rad, "untouched chunk = 0 radiation");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void manager_getProxySingleton(GameTestHelper helper) {
        var proxy1 = ChunkRadiationManager.getProxy();
        var proxy2 = ChunkRadiationManager.getProxy();
        check(proxy1 == proxy2, "getProxy must return a singleton");
        check(proxy1 instanceof ChunkRadiationHandlerSimple,
                "getProxy defaults to ChunkRadiationHandlerSimple");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 3: ChunkRadiationHandlerSimple — get/set/increment/decrement, clearSystem.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void handlerSimple_setGetRadiation(GameTestHelper helper) {
        BlockPos abs = helper.absolutePos(new BlockPos(2, 1, 2));
        Level level = helper.getLevel();
        ChunkRadiationHandlerSimple proxy = (ChunkRadiationHandlerSimple) ChunkRadiationManager.getProxy();
        proxy.setRadiation(level, abs.getX(), abs.getY(), abs.getZ(), 75f);
        float rad = proxy.getRadiation(level, abs.getX(), abs.getY(), abs.getZ());
        checkEq(75f, rad, "handler set→get");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void handlerSimple_incrementDecrement(GameTestHelper helper) {
        BlockPos abs = helper.absolutePos(new BlockPos(2, 1, 2));
        Level level = helper.getLevel();
        ChunkRadiationHandlerSimple proxy = (ChunkRadiationHandlerSimple) ChunkRadiationManager.getProxy();
        proxy.setRadiation(level, abs.getX(), abs.getY(), abs.getZ(), 100f);
        proxy.incrementRad(level, abs.getX(), abs.getY(), abs.getZ(), 50f);
        checkEq(150f, proxy.getRadiation(level, abs.getX(), abs.getY(), abs.getZ()),
                "increment adds");
        proxy.decrementRad(level, abs.getX(), abs.getY(), abs.getZ(), 30f);
        checkEq(120f, proxy.getRadiation(level, abs.getX(), abs.getY(), abs.getZ()),
                "decrement subtracts");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void handlerSimple_decrementBelowZero(GameTestHelper helper) {
        BlockPos abs = helper.absolutePos(new BlockPos(2, 1, 2));
        Level level = helper.getLevel();
        ChunkRadiationHandlerSimple proxy = (ChunkRadiationHandlerSimple) ChunkRadiationManager.getProxy();
        proxy.setRadiation(level, abs.getX(), abs.getY(), abs.getZ(), 10f);
        proxy.decrementRad(level, abs.getX(), abs.getY(), abs.getZ(), 100f);
        checkEq(0f, proxy.getRadiation(level, abs.getX(), abs.getY(), abs.getZ()),
                "decrement below 0 clamps to 0 (Math.max(0, ...))");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void handlerSimple_clearSystem(GameTestHelper helper) {
        Level level = helper.getLevel();
        ChunkRadiationHandlerSimple proxy = (ChunkRadiationHandlerSimple) ChunkRadiationManager.getProxy();
        proxy.clearSystem(level);
        // After clearSystem getRadiation must return 0 (active chunks cleared).
        BlockPos abs = helper.absolutePos(new BlockPos(2, 1, 2));
        proxy.setRadiation(level, abs.getX(), abs.getY(), abs.getZ(), 50f);
        checkEq(50f, proxy.getRadiation(level, abs.getX(), abs.getY(), abs.getZ()),
                "after clearSystem set→get works");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void handlerSimple_getRadiationNullLevel(GameTestHelper helper) {
        ChunkRadiationHandlerSimple proxy = (ChunkRadiationHandlerSimple) ChunkRadiationManager.getProxy();
        checkEq(0f, proxy.getRadiation(null, 0, 0, 0),
                "getRadiation(null, ...) → 0 without crashing");
        proxy.setRadiation(null, 0, 0, 0, 50f);
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 4: PlayerHandler — get/set/increment/decrement, rounding, null-safety.
    //  setPlayerRads: Math.round(Math.max(0, rads) * 10.0f) / 10.0f (rounded to 1 decimal).
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void playerHandler_setGetRads(GameTestHelper helper) {
        Player player = makePlayer(helper);
        PlayerHandler.setPlayerRads(player, 100f);
        checkEq(100f, PlayerHandler.getPlayerRads(player), "set→get round-trip");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void playerHandler_rounding(GameTestHelper helper) {
        Player player = makePlayer(helper);
        PlayerHandler.setPlayerRads(player, 123.456f);
        // Math.round(123.456 * 10) / 10 = Math.round(1234.56) / 10 = 1235 / 10 = 123.5
        checkEq(123.5f, PlayerHandler.getPlayerRads(player),
                "setPlayerRads rounds to 1 decimal place (×10/10)");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void playerHandler_negativeClamps(GameTestHelper helper) {
        Player player = makePlayer(helper);
        PlayerHandler.setPlayerRads(player, -50f);
        checkEq(0f, PlayerHandler.getPlayerRads(player),
                "negative radiation clamps to 0 (Math.max(0, ...))");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void playerHandler_incrementDecrement(GameTestHelper helper) {
        Player player = makePlayer(helper);
        PlayerHandler.setPlayerRads(player, 100f);
        PlayerHandler.incrementPlayerRads(player, 50f);
        checkEq(150f, PlayerHandler.getPlayerRads(player), "increment");
        PlayerHandler.decrementPlayerRads(player, 30f);
        checkEq(120f, PlayerHandler.getPlayerRads(player), "decrement");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void playerHandler_decrementBelowZero(GameTestHelper helper) {
        Player player = makePlayer(helper);
        PlayerHandler.setPlayerRads(player, 10f);
        PlayerHandler.decrementPlayerRads(player, 100f);
        checkEq(0f, PlayerHandler.getPlayerRads(player),
                "decrement below 0 clamps to 0");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void playerHandler_incrementZeroNoOp(GameTestHelper helper) {
        Player player = makePlayer(helper);
        PlayerHandler.setPlayerRads(player, 50f);
        PlayerHandler.incrementPlayerRads(player, 0f);
        checkEq(50f, PlayerHandler.getPlayerRads(player),
                "increment by 0 is a no-op (rads <= 0 return)");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void playerHandler_nullSafety(GameTestHelper helper) {
        checkEq(0f, PlayerHandler.getPlayerRads(null), "getPlayerRads(null) → 0");
        PlayerHandler.setPlayerRads(null, 100f);     // must not crash
        PlayerHandler.incrementPlayerRads(null, 10f);
        PlayerHandler.decrementPlayerRads(null, 10f);
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void playerHandler_defaultZero(GameTestHelper helper) {
        Player player = makePlayer(helper);
        checkEq(0f, PlayerHandler.getPlayerRads(player),
                "a new player: 0 radiation by default");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 5: HbmLivingProps (non-Player) — persistentData on entities.
    //  incrementRadiation cap = 2500F. setRadiation = Math.max(0, rad).
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void livingProps_setGetRadiation(GameTestHelper helper) {
        Cow cow = makeCow(helper.getLevel());
        HbmLivingProps.setRadiation(cow, 50f);
        checkEq(50f, HbmLivingProps.getRadiation(cow), "set→get radiation on Cow");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void livingProps_incrementRadiation(GameTestHelper helper) {
        Cow cow = makeCow(helper.getLevel());
        HbmLivingProps.setRadiation(cow, 100f);
        HbmLivingProps.incrementRadiation(cow, 50f);
        checkEq(150f, HbmLivingProps.getRadiation(cow), "increment on Cow");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void livingProps_cap2500(GameTestHelper helper) {
        Cow cow = makeCow(helper.getLevel());
        HbmLivingProps.setRadiation(cow, 2400f);
        HbmLivingProps.incrementRadiation(cow, 200f);
        // 2400 + 200 = 2600 → cap 2500
        checkEq(2500f, HbmLivingProps.getRadiation(cow),
                "incrementRadiation caps at 2500F");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void livingProps_negativeClamps(GameTestHelper helper) {
        Cow cow = makeCow(helper.getLevel());
        HbmLivingProps.setRadiation(cow, -50f);
        checkEq(0f, HbmLivingProps.getRadiation(cow),
                "setRadiation negative → Math.max(0, rad)");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void livingProps_radEnvRadBuf(GameTestHelper helper) {
        Cow cow = makeCow(helper.getLevel());
        HbmLivingProps.setRadEnv(cow, 5.5f);
        HbmLivingProps.setRadBuf(cow, 7.7f);
        checkEq(5.5f, HbmLivingProps.getRadEnv(cow), "radEnv set→get");
        checkEq(7.7f, HbmLivingProps.getRadBuf(cow), "radBuf set→get");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void livingProps_incrementZeroNoOp(GameTestHelper helper) {
        Cow cow = makeCow(helper.getLevel());
        HbmLivingProps.setRadiation(cow, 50f);
        HbmLivingProps.incrementRadiation(cow, 0f);
        checkEq(50f, HbmLivingProps.getRadiation(cow),
                "increment by 0 is a no-op (rad == 0F return)");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void livingProps_asbestosBlackLungDigamma(GameTestHelper helper) {
        Cow cow = makeCow(helper.getLevel());
        check(0 == HbmLivingProps.getAsbestos(cow), "asbestos defaults to 0");
        HbmLivingProps.incrementAsbestos(cow, 5);
        check(5 == HbmLivingProps.getAsbestos(cow), "asbestos increment");
        check(0 == HbmLivingProps.getBlackLung(cow), "blackLung defaults to 0");
        HbmLivingProps.incrementBlackLung(cow, 3);
        check(3 == HbmLivingProps.getBlackLung(cow), "blackLung increment");
        check(0f == HbmLivingProps.getDigamma(cow), "digamma defaults to 0");
        HbmLivingProps.incrementDigamma(cow, 2.5f);
        checkEq(2.5f, HbmLivingProps.getDigamma(cow), "digamma increment");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 6: HbmLivingProps (Player delegation) — delegates to PlayerHandler.
    //  For Player, getRadiation/setRadiation call PlayerHandler rather than persistentData.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void livingProps_playerDelegation(GameTestHelper helper) {
        Player player = makePlayer(helper);
        HbmLivingProps.setRadiation(player, 80f);
        // For Player, getRadiation delegates to PlayerHandler.getPlayerRads.
        checkEq(80f, HbmLivingProps.getRadiation(player),
                "HbmLivingProps delegates to PlayerHandler for Player");
        checkEq(PlayerHandler.getPlayerRads(player), HbmLivingProps.getRadiation(player),
                "HbmLivingProps == PlayerHandler for Player");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void livingProps_playerIncrement(GameTestHelper helper) {
        Player player = makePlayer(helper);
        HbmLivingProps.setRadiation(player, 100f);
        HbmLivingProps.incrementRadiation(player, 50f);
        checkEq(150f, HbmLivingProps.getRadiation(player),
                "incrementRadiation delegates for Player");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void livingProps_playerKey(GameTestHelper helper) {
        check("NTM_EXT_LIVING".equals(HbmLivingProps.KEY),
                "entity NBT key = NTM_EXT_LIVING (1.7.10 parity)");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 7: ContaminationUtil — contaminate, calculateRadiationMod, isRadImmune.
    //  contaminate: radEnv += amount, then incrementRadiation(amount × radMod).
    //  For non-Player radMod = 1.0. For Player radMod = 10^(-hazmatResistance).
    //  A Player with tickCount < 200 → contaminate returns false (spawn immunity).
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void contaminate_cowRadiation(GameTestHelper helper) {
        Cow cow = makeCow(helper.getLevel());
        boolean result = ContaminationUtil.contaminate(cow,
                HazardType.RADIATION, ContaminationType.CREATIVE, 10f);
        check(result, "contaminate Cow RADIATION CREATIVE → true (not immune)");
        checkEq(10f, HbmLivingProps.getRadiation(cow),
                "contaminate increments radiation on Cow (radMod=1.0)");
        checkEq(10f, HbmLivingProps.getRadEnv(cow),
                "contaminate accumulates radEnv");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void contaminate_radEnvAccumulates(GameTestHelper helper) {
        Cow cow = makeCow(helper.getLevel());
        ContaminationUtil.contaminate(cow, HazardType.RADIATION, ContaminationType.CREATIVE, 5f);
        ContaminationUtil.contaminate(cow, HazardType.RADIATION, ContaminationType.CREATIVE, 3f);
        checkEq(8f, HbmLivingProps.getRadEnv(cow),
                "radEnv accumulates (5 + 3 = 8)");
        checkEq(8f, HbmLivingProps.getRadiation(cow),
                "radiation accumulates (5 + 3 = 8, radMod=1.0)");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void contaminate_playerTickCountGate(GameTestHelper helper) {
        Player player = makePlayer(helper);
        // Freshly created player: tickCount < 200 → contaminate returns false.
        check(player.tickCount < 200, "mock player tickCount < 200");
        boolean result = ContaminationUtil.contaminate(player,
                HazardType.RADIATION, ContaminationType.CREATIVE, 10f);
        check(!result, "contaminate Player with tickCount < 200 → false (spawn immunity)");
        checkEq(0f, PlayerHandler.getPlayerRads(player),
                "radiation unchanged when tickCount < 200");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void contaminate_radImmuneCow(GameTestHelper helper) {
        Cow cow = makeCow(helper.getLevel());
        // A Cow is NOT immune (only MushroomCow is immune).
        check(!ContaminationUtil.isRadImmune(cow), "Cow is not radiation-immune");
        boolean result = ContaminationUtil.contaminate(cow,
                HazardType.RADIATION, ContaminationType.CREATIVE, 10f);
        check(result, "contaminate Cow → true");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void contaminate_radImmuneZombie(GameTestHelper helper) {
        Zombie zombie = EntityType.ZOMBIE.create(helper.getLevel());
        check(zombie != null, "Zombie must be creatable");
        zombie.moveTo(1.0, 1.0, 1.0);
        check(ContaminationUtil.isRadImmune(zombie), "Zombie is radiation-immune");
        boolean result = ContaminationUtil.contaminate(zombie,
                HazardType.RADIATION, ContaminationType.CREATIVE, 10f);
        check(!result, "contaminate Zombie RADIATION → false (immune)");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void calcRadMod_noArmor(GameTestHelper helper) {
        Player player = makePlayer(helper);
        // Without armor: HazmatRegistry.getResistance = 0 → 10^(-0) = 10^0 = 1.0.
        float mod = ContaminationUtil.calculateRadiationMod(player);
        checkEq(1.0f, mod, "calculateRadiationMod without armor = 1.0 (no protection)");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void calcRadMod_nonPlayer(GameTestHelper helper) {
        Cow cow = makeCow(helper.getLevel());
        // Non-Player → always 1.0.
        float mod = ContaminationUtil.calculateRadiationMod(cow);
        checkEq(1.0f, mod, "calculateRadiationMod non-Player = 1.0");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void isRadImmune_nonLiving(GameTestHelper helper) {
        // Non-LivingEntity → false.
        check(!ContaminationUtil.isRadImmune(null),
                "isRadImmune(null) → false (not a LivingEntity)");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazardType_enumValues(GameTestHelper helper) {
        check(HazardType.RADIATION != HazardType.DIGAMMA,
                "HazardType.RADIATION ≠ DIGAMMA");
        check(ContaminationType.CREATIVE != ContaminationType.HAZMAT,
                "ContaminationType.CREATIVE ≠ HAZMAT");
        check(ContaminationType.NONE != ContaminationType.RAD_BYPASS,
                "ContaminationType.NONE ≠ RAD_BYPASS");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 8: HazmatRegistry — getResistance(ItemStack), getResistance(Player).
    //  Coefficients: HELMET=0.2, CHEST=0.4, LEGS=0.3, BOOTS=0.1.
    //  HAZMAT set: hazYellow=0.6 → helmet=0.12, chest=0.24, legs=0.18, boots=0.06.
    //  Iron: 0.0225 → helmet=0.0045. Diamond helmet=0.05.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazmat_emptyStack(GameTestHelper helper) {
        check(0.0 == HazmatRegistry.getResistance(ItemStack.EMPTY),
                "getResistance(EMPTY) → 0");
        check(0.0 == HazmatRegistry.getResistance((ItemStack) null),
                "getResistance(null) → 0");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazmat_nonArmorItem(GameTestHelper helper) {
        // An item with no registered resistance → only cladding (0).
        double res = HazmatRegistry.getResistance(new ItemStack(Items.STICK));
        check(0.0 == res, "getResistance(non-armor) → 0 (cladding=0)");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazmat_ironHelmet(GameTestHelper helper) {
        // Iron: 0.0225 × HELMET(0.2) = 0.0045.
        double res = HazmatRegistry.getResistance(new ItemStack(Items.IRON_HELMET));
        check(Math.abs(res - 0.0045) < 1e-6,
                "iron helmet resistance = 0.0225 × 0.2 = 0.0045 (got " + res + ")");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazmat_diamondChestplate(GameTestHelper helper) {
        // Diamond chestplate: 0.25 (hardcoded).
        double res = HazmatRegistry.getResistance(new ItemStack(Items.DIAMOND_CHESTPLATE));
        check(Math.abs(res - 0.25) < 1e-6,
                "diamond chestplate resistance = 0.25 (got " + res + ")");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazmat_hazmatHelmet(GameTestHelper helper) {
        // HAZMAT helmet: hazYellow(0.6) × HELMET(0.2) = 0.12.
        double res = HazmatRegistry.getResistance(
                new ItemStack(ModItems.HAZMAT_HELMET.get()));
        check(Math.abs(res - 0.12) < 1e-6,
                "hazmat helmet resistance = 0.6 × 0.2 = 0.12 (got " + res + ")");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void hazmat_playerNoArmor(GameTestHelper helper) {
        Player player = makePlayer(helper);
        // Without armor → getResistance(Player) = 0.
        float res = HazmatRegistry.getResistance(player);
        check(Math.abs(res) < 1e-6, "player without armor → resistance 0");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazmat_claddingZero(GameTestHelper helper) {
        // getCladding always returns 0 in the current implementation.
        check(0f == HazmatRegistry.getCladding(new ItemStack(Items.IRON_HELMET)),
                "getCladding → 0 (no cladding implementation)");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 9: HazardSystem — getHazardLevelFromStack, getHazardsFromStack,
    //  getHazardLevelFromState, cache, sellafiteRadiationForLevel.
    //  Registration: HazardRegistry.registerItems() is called in MainRegistry.setup.
    //  CRYSTAL_URANIUM=3.5f, CRYSTAL_THORIUM=1.0f, POLONIUM210_BLOCK=750f.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazard_crystalUranium(GameTestHelper helper) {
        float level = HazardSystem.getHazardLevelFromStack(
                new ItemStack(ModItems.CRYSTAL_URANIUM.get()), HazardRegistry.RADIATION);
        checkEq(3.5f, level, "CRYSTAL_URANIUM radiation hazard = 3.5f");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazard_crystalThorium(GameTestHelper helper) {
        float level = HazardSystem.getHazardLevelFromStack(
                new ItemStack(ModItems.CRYSTAL_THORIUM.get()), HazardRegistry.RADIATION);
        checkEq(1.0f, level, "CRYSTAL_THORIUM radiation hazard = 1.0f");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazard_nonRadioactiveItem(GameTestHelper helper) {
        // Iron ingot is not registered with a RADIATION hazard.
        float level = HazardSystem.getHazardLevelFromStack(
                new ItemStack(Items.IRON_INGOT), HazardRegistry.RADIATION);
        checkEq(0.0f, level, "IRON_INGOT radiation = 0 (not radioactive)");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazard_emptyStack(GameTestHelper helper) {
        check(HazardSystem.getHazardsFromStack(ItemStack.EMPTY).isEmpty(),
                "getHazardsFromStack(EMPTY) → empty list");
        check(HazardSystem.getHazardsFromStack(null).isEmpty(),
                "getHazardsFromStack(null) → empty list");
        checkEq(0.0f, HazardSystem.getHazardLevelFromStack(null, HazardRegistry.RADIATION),
                "getHazardLevelFromStack(null) → 0");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazard_cacheConsistency(GameTestHelper helper) {
        // The cache must return the same list for the same Item.
        var list1 = HazardSystem.getHazardsFromStack(
                new ItemStack(ModItems.CRYSTAL_URANIUM.get()));
        var list2 = HazardSystem.getHazardsFromStack(
                new ItemStack(ModItems.CRYSTAL_URANIUM.get()));
        check(list1 == list2, "HAZARD_CACHE returns the same list (identity)");
        check(!list1.isEmpty(), "CRYSTAL_URANIUM has hazards");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazard_getHazardLevelFromState(GameTestHelper helper) {
        // Iron block → asItem → iron_ingot → not radioactive → 0.
        BlockState state = Blocks.IRON_BLOCK.defaultBlockState();
        float level = HazardSystem.getHazardLevelFromState(state, HazardRegistry.RADIATION);
        checkEq(0.0f, level, "IRON_BLOCK state radiation = 0");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazard_getHazardLevelFromStateAir(GameTestHelper helper) {
        BlockState air = Blocks.AIR.defaultBlockState();
        checkEq(0.0f, HazardSystem.getHazardLevelFromState(air, HazardRegistry.RADIATION),
                "AIR state radiation = 0");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazard_sellafiteRadiationForLevel(GameTestHelper helper) {
        // sellafiteRadiationForLevel: 0→0.5, 1→1.0, 2→2.5, 3→4.0, 4→5.0, 5→10.0,
        // 6→15.0, 7→20.0, 8→25.0, 9→30.0, 10→35.0.
        checkEq(0.5f, HazardSystem.sellafiteRadiationForLevel(0), "sellafite level 0 = 0.5");
        checkEq(1.0f, HazardSystem.sellafiteRadiationForLevel(1), "sellafite level 1 = 1.0");
        checkEq(2.5f, HazardSystem.sellafiteRadiationForLevel(2), "sellafite level 2 = 2.5");
        checkEq(4.0f, HazardSystem.sellafiteRadiationForLevel(3), "sellafite level 3 = 4.0");
        checkEq(5.0f, HazardSystem.sellafiteRadiationForLevel(4), "sellafite level 4 = 5.0");
        checkEq(10.0f, HazardSystem.sellafiteRadiationForLevel(5), "sellafite level 5 = 10.0");
        checkEq(15.0f, HazardSystem.sellafiteRadiationForLevel(6), "sellafite level 6 = 15.0");
        checkEq(35.0f, HazardSystem.sellafiteRadiationForLevel(10), "sellafite level 10 = 35.0");
        // Clamp: -5 → 0 → 0.5, 100 → 10 → 35.0.
        checkEq(0.5f, HazardSystem.sellafiteRadiationForLevel(-5), "sellafite -5 clamps to 0 = 0.5");
        checkEq(35.0f, HazardSystem.sellafiteRadiationForLevel(100), "sellafite 100 clamps to 10 = 35.0");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazard_getArmorProtection(GameTestHelper helper) {
        // getArmorProtection delegates to HazmatRegistry.getResistance.
        float prot = HazardSystem.getArmorProtection(new ItemStack(Items.IRON_HELMET));
        check(Math.abs(prot - 0.0045f) < 1e-5f,
                "getArmorProtection(iron helmet) = 0.0045 (got " + prot + ")");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazard_applyHazardsNoCrash(GameTestHelper helper) {
        // applyHazards on a non-radioactive item — must not crash.
        Cow cow = makeCow(helper.getLevel());
        HazardSystem.applyHazards(new ItemStack(Items.STICK), cow);
        HazardSystem.applyHazards(ItemStack.EMPTY, cow);
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 10: HazardRegistry — RADIATION singleton identity.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazardRegistry_radiationSingleton(GameTestHelper helper) {
        check(HazardRegistry.RADIATION != null, "RADIATION singleton is not null");
        check(HazardRegistry.RADIATION instanceof com.hbm_m.hazard.type.HazardTypeRadiation,
                "RADIATION — instanceof HazardTypeRadiation");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazardRegistry_allTypesNonNull(GameTestHelper helper) {
        check(HazardRegistry.RADIATION != null, "RADIATION");
        check(HazardRegistry.HOT != null, "HOT");
        check(HazardRegistry.DIGAMMA != null, "DIGAMMA");
        check(HazardRegistry.BLINDING != null, "BLINDING");
        check(HazardRegistry.ASBESTOS != null, "ASBESTOS");
        check(HazardRegistry.COAL != null, "COAL");
        check(HazardRegistry.HYDROACTIVE != null, "HYDROACTIVE");
        check(HazardRegistry.EXPLOSIVE != null, "EXPLOSIVE");
        // All distinct singletons.
        check(HazardRegistry.RADIATION != HazardRegistry.HOT, "RADIATION ≠ HOT");
        check(HazardRegistry.RADIATION != HazardRegistry.DIGAMMA, "RADIATION ≠ DIGAMMA");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 11: HazardData / HazardEntry — override, mutex, baseLevel, addMod.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazardEntry_baseLevel(GameTestHelper helper) {
        HazardEntry entry = new HazardEntry(HazardRegistry.RADIATION, 5.0f);
        checkEq(5.0f, entry.baseLevel, "baseLevel = 5.0");
        check(entry.type == HazardRegistry.RADIATION, "type = RADIATION");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazardEntry_defaultLevel(GameTestHelper helper) {
        HazardEntry entry = new HazardEntry(HazardRegistry.RADIATION);
        checkEq(1.0f, entry.baseLevel, "default baseLevel = 1.0F");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazardEntry_addMod(GameTestHelper helper) {
        HazardEntry entry = new HazardEntry(HazardRegistry.RADIATION, 5.0f);
        int before = entry.mods.size();
        HazardEntry returned = entry.addMod(null); // addMod accepts a HazardModifier
        check(returned == entry, "addMod returns this (builder pattern)");
        check(entry.mods.size() == before + 1, "addMod adds a modifier to the list");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazardData_overrideAndMutex(GameTestHelper helper) {
        HazardData data = new HazardData(
                new HazardEntry(HazardRegistry.RADIATION, 10f));
        check(!data.doesOverride, "doesOverride defaults to false");
        check(0 == data.getMutex(), "mutex defaults to 0");
        HazardData returned = data.setAsOverride();
        check(returned == data, "setAsOverride returns this");
        check(data.doesOverride, "doesOverride true after setAsOverride");
        check(!data.entries.isEmpty(), "entries is not empty");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void hazardEntry_applyHazardNoCrash(GameTestHelper helper) {
        // applyHazard calls type.onUpdate — for RADIATION this is contaminate.
        // On a Cow (not a Player, tickCount is not checked) it should work.
        Cow cow = makeCow(helper.getLevel());
        HazardEntry entry = new HazardEntry(HazardRegistry.RADIATION, 10f);
        entry.applyHazard(new ItemStack(ModItems.CRYSTAL_URANIUM.get()), cow);
        // onUpdate: level × count / 20F → 3.5 × 1 / 20 = 0.175 → contaminate CREATIVE.
        check(HbmLivingProps.getRadiation(cow) > 0f,
                "applyHazard RADIATION accumulates radiation on Cow");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 12: EntityEffectHandler — radBuf snap (tickCount % 20 == 0),
    //  kill threshold of 1000 RAD (Pig, not Cow/Villager/Creeper).
    //  onUpdate: every 20 ticks setRadBuf(getRadEnv) + setRadEnv(0).
    //  handleRadiationEffect: eRad >= 1000 → hurt(1000) + setRadiation(0) + die.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void entityEffect_radBufSnap(GameTestHelper helper) {
        Level level = helper.getLevel();
        // Place the entity INSIDE the structure (via absolutePos) and clear the chunk
        // radiation at that position — isolation from previous manager_setGetRadiation.
        BlockPos abs = helper.absolutePos(new BlockPos(1, 1, 1));
        ChunkRadiationManager.setRadiation(level, abs.getX(), abs.getY(), abs.getZ(), 0f);
        Cow cow = makeCowAt(helper);
        // A freshly created entity: tickCount = 0 → 0 % 20 == 0 → snap happens.
        check(cow.tickCount == 0, "Cow tickCount == 0 on creation");
        HbmLivingProps.setRadEnv(cow, 5.0f);
        checkEq(5.0f, HbmLivingProps.getRadEnv(cow), "radEnv set");
        // onUpdate: setRadBuf(getRadEnv) + setRadEnv(0).
        EntityEffectHandler.onUpdate(cow);
        checkEq(5.0f, HbmLivingProps.getRadBuf(cow),
                "radBuf = old radEnv after snap");
        checkEq(0.0f, HbmLivingProps.getRadEnv(cow),
                "radEnv reset to 0 after snap");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void entityEffect_lowRadNoEffect(GameTestHelper helper) {
        Level level = helper.getLevel();
        // Clear the chunk radiation at the structure position (test isolation).
        BlockPos abs = helper.absolutePos(new BlockPos(1, 1, 1));
        ChunkRadiationManager.setRadiation(level, abs.getX(), abs.getY(), abs.getZ(), 0f);
        Cow cow = makeCowAt(helper);
        HbmLivingProps.setRadiation(cow, 50f);
        // eRad = 50 < 200 → handleRadiationEffect early return.
        // But a Cow at eRad >= 50 → Cow→Mooshroom transformation! Use a Pig instead.
        Pig pig = makePigAt(helper);
        HbmLivingProps.setRadiation(pig, 50f);
        float healthBefore = pig.getHealth();
        EntityEffectHandler.onUpdate(pig);
        check(pig.isAlive(), "Pig at 50 RAD alive (eRad < 200)");
        // handleRadiationEffect at eRad < 200 does not change radiation; handleRadiationFromChunk
        // adds rad/20F from the chunk (cleared → 0). Verify exact equality.
        checkEq(50f, HbmLivingProps.getRadiation(pig),
                "Pig at 50 RAD: radiation unchanged");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void entityEffect_killAt1000(GameTestHelper helper) {
        Level level = helper.getLevel();
        // Clear the chunk radiation at the structure position (test isolation).
        BlockPos abs = helper.absolutePos(new BlockPos(1, 1, 1));
        ChunkRadiationManager.setRadiation(level, abs.getX(), abs.getY(), abs.getZ(), 0f);
        Pig pig = makePigAt(helper);
        HbmLivingProps.setRadiation(pig, 1000f);
        checkEq(1000f, HbmLivingProps.getRadiation(pig), "Pig rad = 1000 before onUpdate");
        float healthBefore = pig.getHealth();
        check(healthBefore > 0f, "Pig alive before onUpdate");
        EntityEffectHandler.onUpdate(pig);
        // eRad >= 1000 → hurt(1000) + setRadiation(0) + if health > 0 setHealth(0) + die.
        check(pig.isDeadOrDying() || pig.getHealth() <= 0f,
                "Pig at 1000 RAD dead/dying after onUpdate");
        // After the kill setRadiation(0); handleRadiationFromChunk adds rad/20F from the chunk
        // (cleared → 0). Verify exact equality to 0.
        checkEq(0f, HbmLivingProps.getRadiation(pig),
                "Pig radiation reset to 0 after kill (1000 RAD)");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void entityEffect_radImmuneNoKill(GameTestHelper helper) {
        // A Zombie is immune — handleRadiationEffect early returns (isRadImmune).
        Zombie zombie = EntityType.ZOMBIE.create(helper.getLevel());
        check(zombie != null, "Zombie must be creatable");
        zombie.moveTo(1.0, 1.0, 1.0);
        HbmLivingProps.setRadiation(zombie, 1000f);
        float healthBefore = zombie.getHealth();
        EntityEffectHandler.onUpdate(zombie);
        check(zombie.isAlive(), "Zombie at 1000 RAD alive (immune)");
        check(zombie.getHealth() > 0f, "Zombie health > 0 (immune)");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 13: HazardTypeRadiation — onUpdate: rad = level / 20F.
    //  level *= stack.getCount(). Without reacher: rad = level / 20F.
    //  CRYSTAL_URANIUM: hazard=3.5, 1 item → onUpdate → 3.5×1/20 = 0.175 RAD.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void hazardTypeRadiation_onUpdateCow(GameTestHelper helper) {
        Cow cow = makeCow(helper.getLevel());
        // CRYSTAL_URANIUM × 1: hazard=3.5, onUpdate → rad = 3.5×1/20 = 0.175.
        ItemStack stack = new ItemStack(ModItems.CRYSTAL_URANIUM.get(), 1);
        HazardSystem.applyHazards(stack, cow);
        // applyHazards → HazardTypeRadiation.onUpdate → contaminate CREATIVE →
        // radEnv += 0.175, incrementRadiation += 0.175 (radMod=1.0 for Cow).
        check(HbmLivingProps.getRadiation(cow) > 0f,
                "CRYSTAL_URANIUM pumps radiation into the Cow");
        check(HbmLivingProps.getRadEnv(cow) > 0f,
                "CRYSTAL_URANIUM accumulates radEnv");
        // Exact value: 3.5 / 20 = 0.175.
        checkEq(0.175f, HbmLivingProps.getRadiation(cow),
                "CRYSTAL_URANIUM ×1: rad = 3.5 / 20 = 0.175");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void hazardTypeRadiation_stackCount(GameTestHelper helper) {
        Cow cow = makeCow(helper.getLevel());
        // CRYSTAL_URANIUM × 4: hazard=3.5, onUpdate → rad = 3.5×4/20 = 0.7.
        ItemStack stack = new ItemStack(ModItems.CRYSTAL_URANIUM.get(), 4);
        HazardSystem.applyHazards(stack, cow);
        checkEq(0.7f, HbmLivingProps.getRadiation(cow),
                "CRYSTAL_URANIUM ×4: rad = 3.5 × 4 / 20 = 0.7");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void hazardTypeRadiation_nonRadioactiveNoEffect(GameTestHelper helper) {
        Cow cow = makeCow(helper.getLevel());
        // STICK has no RADIATION hazard → applyHazards does not call onUpdate.
        HazardSystem.applyHazards(new ItemStack(Items.STICK), cow);
        checkEq(0f, HbmLivingProps.getRadiation(cow),
                "STICK pumps no radiation");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 14: PlayerHandler.getInventoryRadiation — sum of radioactive items
    //  in the inventory. getRadiationFromItemStack = hazard × count.
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void playerHandler_inventoryRadiationEmpty(GameTestHelper helper) {
        Player player = makePlayer(helper);
        checkEq(0f, PlayerHandler.getInventoryRadiation(player),
                "empty inventory → 0 inventory radiation");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void playerHandler_inventoryRadiationItem(GameTestHelper helper) {
        Player player = makePlayer(helper);
        // CRYSTAL_URANIUM × 2: hazard=3.5 × count=2 = 7.0.
        player.getInventory().add(new ItemStack(ModItems.CRYSTAL_URANIUM.get(), 2));
        float invRad = PlayerHandler.getInventoryRadiation(player);
        checkEq(7.0f, invRad,
                "CRYSTAL_URANIUM ×2: inventory radiation = 3.5 × 2 = 7.0");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void playerHandler_inventoryRadiationNonRadioactive(GameTestHelper helper) {
        Player player = makePlayer(helper);
        player.getInventory().add(new ItemStack(Items.IRON_INGOT, 64));
        checkEq(0f, PlayerHandler.getInventoryRadiation(player),
                "IRON_INGOT ×64: inventory radiation = 0 (not radioactive)");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 15: PlayerHandler.getIncomingEnvironmentRad — radBuf on the Geiger counter.
    //  getIncomingEnvironmentRad = HbmLivingProps.getRadBuf(player).
    // ════════════════════════════════════════════════════════════════════════

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void playerHandler_incomingEnvRadDefault(GameTestHelper helper) {
        Player player = makePlayer(helper);
        checkEq(0f, PlayerHandler.getIncomingEnvironmentRad(player),
                "incomingEnvRad defaults to 0 (radBuf = 0)");
        helper.succeed();
    }

    @GameTest(template = "empty5x5x5", batch = "radiation", timeoutTicks = 100)
    public static void playerHandler_incomingEnvRadAfterSet(GameTestHelper helper) {
        Player player = makePlayer(helper);
        HbmLivingProps.setRadBuf(player, 15.0f);
        checkEq(15.0f, PlayerHandler.getIncomingEnvironmentRad(player),
                "incomingEnvRad = radBuf after set");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void playerHandler_incomingEnvRadNull(GameTestHelper helper) {
        checkEq(0f, PlayerHandler.getIncomingEnvironmentRad(null),
                "incomingEnvRad(null) → 0");
        helper.succeed();
    }

    // ════════════════════════════════════════════════════════════════════════
    //  Group 16: Network — radiation S2C channels.
    //
    //  Radiation delivery to the client goes through three S2C channels (Architectury NetworkManager):
    //   • radiation_data          — HUD Geiger counter (env + accumulated player dose);
    //   • chunk_rad_debug_batch   — 3D debug rendering of chunk radiation;
    //   • geiger_sound            — Geiger counter sounds from armor/devices.
    //
    //  A GameTest runs on the logical server, so a full round-trip to the client
    //  is unavailable. We verify the server half of the pipeline:
    //   1) S2C payloads are registered (>= 1.21.1: the NetworkAggregator.S2C_TYPE map —
    //      without it NeoForge's checkPacket rejects sending and Architectury returns a null type);
    //   2) outbound buf→Packet conversion works for each channel — exactly the path
    //      ModPacketHandler.sendToPlayer uses before handing off to the connection;
    //   3) codecs are symmetric: write→decode reproduces the payload bytes.
    // ════════════════════════════════════════════════════════════════════════

    /** S2C channels of the radiation system. */
    private static final ResourceLocation[] RADIATION_S2C_CHANNELS = {
            ModPacketHandler.RADIATION_DATA,
            ModPacketHandler.CHUNK_RAD_DEBUG_BATCH,
            ModPacketHandler.GEIGER_SOUND,
    };

    /**
     * Writes a payload via writer and converts it to an outgoing S2C Packet —
     * the same sequence as in {@code ModPacketHandler.sendToPlayer} prior to sending.
     */
    private static Packet<?> buildS2CPacket(GameTestHelper helper, ResourceLocation id,
                                            java.util.function.Consumer<FriendlyByteBuf> writer) {
        //? if < 1.21.1 {
        FriendlyByteBuf buf = new FriendlyByteBuf(Unpooled.buffer());
        writer.accept(buf);
        return NetworkManager.toPacket(NetworkManager.Side.S2C, id, buf);
        //?} else {
        /*net.minecraft.network.RegistryFriendlyByteBuf buf = new net.minecraft.network.RegistryFriendlyByteBuf(
                Unpooled.buffer(), helper.getLevel().getServer().registryAccess());
        writer.accept(buf);
        return NetworkManager.toPacket(NetworkManager.Side.S2C, id, buf);
        *///?}
    }

    /** Codec symmetry: write → decode → write must produce identical bytes. */
    private static <T extends com.hbm_m.network.S2CPacket> void checkCodecRoundtrip(
            T original, java.util.function.Function<FriendlyByteBuf, T> decoder, String label) {
        FriendlyByteBuf encoded = new FriendlyByteBuf(Unpooled.buffer());
        original.write(encoded);
        T decoded = decoder.apply(new FriendlyByteBuf(encoded.copy()));
        FriendlyByteBuf reencoded = new FriendlyByteBuf(Unpooled.buffer());
        decoded.write(reencoded);
        String a = ByteBufUtil.hexDump(encoded.copy());
        String b = ByteBufUtil.hexDump(reencoded);
        check(a.equals(b), label + ": write→decode→write changed the payload bytes (" + a + " != " + b + ")");
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void network_radiationS2cChannelsReady(GameTestHelper helper) {
        // 1. Payload registration. On >= 1.21.1 the payload participates in negotiation:
        // an undeclared channel is rejected by NeoForge on send (checkPacket),
        // and Architectury takes the type from the same map during conversion.
        //? if >= 1.21.1 {
        /*for (ResourceLocation id : RADIATION_S2C_CHANNELS) {
            check(dev.architectury.impl.NetworkAggregator.S2C_TYPE.containsKey(id),
                    "S2C payload type not registered: " + id);
        }
        *///?}
        // 2. Outbound conversion for each channel.
        for (ResourceLocation id : RADIATION_S2C_CHANNELS) {
            Packet<?> out = buildS2CPacket(helper, id, buf -> { });
            check(out != null, "toPacket(S2C) returned null for channel " + id);
        }
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void network_radiationDataPacketCodecRoundtrip(GameTestHelper helper) {
        checkCodecRoundtrip(new RadiationDataPacket(12.5f, 777.25f),
                RadiationDataPacket::decode, "RadiationDataPacket");
        checkCodecRoundtrip(new RadiationDataPacket(0f, 0f),
                RadiationDataPacket::decode, "RadiationDataPacket(zero values)");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void network_geigerSoundPacketCodecRoundtrip(GameTestHelper helper) {
        checkCodecRoundtrip(new GeigerSoundPacket(
                        ResourceLocation.fromNamespaceAndPath(RefStrings.MODID, "geiger_1"), 0.75f, 1.25f),
                GeigerSoundPacket::decode, "GeigerSoundPacket");
        checkCodecRoundtrip(new GeigerSoundPacket(
                        ResourceLocation.fromNamespaceAndPath("minecraft", "entity.experience_orb.pickup"), 1f, 0.5f),
                GeigerSoundPacket::decode, "GeigerSoundPacket(foreign namespace)");
        helper.succeed();
    }

    @GameTest(template = "empty3x3x3", batch = "radiation", timeoutTicks = 100)
    public static void network_chunkRadDebugBatchPacketCodecRoundtrip(GameTestHelper helper) {
        Map<ChunkPos, Float> data = new HashMap<>();
        data.put(new ChunkPos(10, -4), 55.5f);
        data.put(new ChunkPos(0, 0), 0.125f);
        data.put(new ChunkPos(-123456, 654321), 99999.0f);
        ResourceLocation dim = ResourceLocation.fromNamespaceAndPath(RefStrings.MODID, "overworld_test");
        checkCodecRoundtrip(new ChunkRadiationDebugBatchPacket(data, dim),
                ChunkRadiationDebugBatchPacket::decode, "ChunkRadiationDebugBatchPacket");

        // Empty map — the server sends empty batches when there are no changes.
        checkCodecRoundtrip(new ChunkRadiationDebugBatchPacket(new HashMap<>(), dim),
                ChunkRadiationDebugBatchPacket::decode, "ChunkRadiationDebugBatchPacket(empty map)");

        // Outbound conversion of a real batch over the debug-render channel.
        Packet<?> out = buildS2CPacket(helper, ModPacketHandler.CHUNK_RAD_DEBUG_BATCH,
                buf -> new ChunkRadiationDebugBatchPacket(data, dim).write(buf));
        check(out != null, "toPacket(S2C) returned null for chunk_rad_debug_batch");
        helper.succeed();
    }
}
