project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN

preserve_hierarchy: true

files:
  - source: /src/generated/resources/assets/hbm_m/lang/en_us.json
    translation: /src/generated/resources/assets/hbm_m/lang/%locale_with_underscore%.json
    
    ignore:
      - /src/generated/resources/assets/hbm_m/lang/ru_ru.json

    languages_mapping:
      locale_with_underscore:
        af: af_za
        ar: ar_sa
        ast: ast_es
        az: az_az
        ba: ba_ru
        be: be_by
        bg: bg_bg
        br: br_fr
        bs: bs_ba
        ca: ca_es
        cs: cs_cz
        cy: cy_gb
        da: da_dk
        de: de_de
        el: el_gr
        en-AU: en_au
        en-CA: en_ca
        en-GB: en_gb
        en-NZ: en_nz
        en-PT: en_pt
        en-UD: en_ud
        eo: eo_uy
        es-AR: es_ar
        es-CL: es_cl
        es-EC: es_ec
        es-ES: es_es
        es-MX: es_mx
        es-UY: es_uy
        es-VE: es_ve
        et: et_ee
        eu: eu_es
        fa: fa_ir
        fi: fi_fi
        fil: fil_ph
        fo: fo_fo
        fr-CA: fr_ca
        fr: fr_fr
        fy-NL: fy_nl
        ga-IE: ga_ie
        gd: gd_gb
        gl: gl_es
        haw: haw_us
        he: he_il
        hi: hi_in
        hr: hr_hr
        hu: hu_hu
        hy-AM: hy_am
        id: id_id
        ig: ig_ng
        is: is_is
        it: it_it
        ja: ja_jp
        ka: ka_ge
        kk: kk_kz
        kn: kn_in
        ko: ko_kr
        ksh: ksh
        kw: kw_gb
        la-LA: la_la
        lb: lb_lu
        li: li_li
        lol: lol_us
        lt: lt_lt
        lv: lv_lv
        lzh: lzh
        mk: mk_mk
        mn: mn_mn
        ms: ms_my
        mt: mt_mt
        nds: nds_de
        nl-BE: nl_be
        nl: nl_nl
        nn-NO: nn_no
        no: no_no
        oc: oc_fr
        pl: pl_pl
        pt-BR: pt_br
        pt-PT: pt_pt
        qya-AA: qya_aa
        ro: ro_ro
        ru: ru_ru
        sk: sk_sk
        sl: sl_si
        so: so_so
        sq: sq_al
        sr: sr_sp
        sv-SE: sv_se
        ta: ta_in
        th: th_th
        tlh-AA: tlh_aa
        tr: tr_tr
        tt-RU: tt_ru
        uk: uk_ua
        val-ES: val_es
        vec: vec_it
        vi: vi_vn
        yi: yi_de
        yo: yo_ng
        zh-CN: zh_cn
        zh-HK: zh_hk
        zh-TW: zh_tw
