org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false
systemProp.org.gradle.internal.http.socketTimeout=180000
systemProp.org.gradle.internal.http.connectionTimeout=45000

mod.id=hbm_m
mod.name=HBM's Nuclear Tech Modernized
mod.group=com
mod.version=0.2.2-alpha
mod.channel_tag=
mod.authors=RaptorDev, TRFFuchs, razchexlitiel, HyperiO
mod.contributors=ThePhoenixKnight, boryu._. (ko_kr translation), hexagon_inc (.dae parser), kami_no_samurai (fr_fr translation)
mod.license=GNU General Public License v3.0
mod.description=A rewritten version from scratch of the well-known HBM's Nuclear Tech mod for Forge 1.20.1.\nContains very little content at the moment, but our team constantly working on it...
mod.sources_url=https://github.com/Raptor324/HBM-Modernized
mod.homepage_url=https://modrinth.com/mod/hbms-nuclear-tech-modernized
mod.issues_url=https://github.com/Raptor324/HBM-Modernized/issues
mod.discord_url=https://discord.com/invite/f2BhvzG6CS
mod.mixin_config=mixins.hbm_m.json
mod.mixin_refmap=mixins.hbm_m.refmap.json

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.forge=[VERSIONED]
deps.architectury=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.create=[VERSIONED]
deps.flywheel=[VERSIONED]
deps.jei=[VERSIONED]

publish.modrinth=
publish.curseforge=
publish.github=false
