deps.minecraft=1.21.1
deps.neoforge=21.1.248
deps.architectury=13.0.11
deps.parchment=1.21.1:2024.11.17
deps.create=6.0.10-280
deps.flywheel=1.0.6
deps.jei=8569044
deps.minecraft_dependency_range=[1.21.1]

publish.additionalVersions=
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-21.0.9.10-hotspot