package com.hbm_m.datagen.recipes.custom;
//? if forge {
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Inhalt der OreDict-Tags {@code hbm_m:oredict/...}: je Original-Schluessel (z. B. {@code plateTripleSteel})
 * die Port-Gegenstaende, die das Original darunter registriert (OreDictManager, Mats-Autogen, DictGroup),
 * plus die gleichnamigen Forge-Tags (optional, Endung {@code ?}). AUTOMATISCH ERZEUGT durch
 * {@code rc/transpile.py}.
 */
public final class OreDictTagData {

    private OreDictTagData() {}

    public static final Map<String, List<String>> TAGS = new LinkedHashMap<>();

    private static void put(String path, String... entries) {
        TAGS.put(path, List.of(entries));
    }

    static {
        put("oredict/any/ash", "hbm_m:ash_wood", "hbm_m:ash_coal", "hbm_m:ash_misc", "hbm_m:ash_fly", "hbm_m:ash_soot");
        put("oredict/any/concrete", "hbm_m:concrete", "hbm_m:concrete_smooth", "hbm_m:concrete_asbestos", "hbm_m:ducrete", "hbm_m:ducrete_smooth");
        put("oredict/any/tar", "hbm_m:oil_tar_crude", "hbm_m:oil_tar_coal", "hbm_m:oil_tar_crack", "hbm_m:oil_tar_wood");
        put("oredict/billet/americium_rg", "hbm_m:billet_am_mix");
        put("oredict/billet/bismuth", "hbm_m:billet_bismuth");
        put("oredict/billet/gold198", "hbm_m:billet_au198");
        put("oredict/billet/lead209", "hbm_m:billet_pb209");
        put("oredict/billet/plutonium239", "hbm_m:billet_pu239");
        put("oredict/billet/plutonium240", "hbm_m:billet_pu240");
        put("oredict/billet/plutonium241", "hbm_m:billet_pu241");
        put("oredict/billet/plutonium_rg", "hbm_m:billet_pu_mix");
        put("oredict/billet/polonium210", "hbm_m:billet_polonium");
        put("oredict/billet/silicon", "hbm_m:billet_silicon");
        put("oredict/billet/uranium", "hbm_m:billet_uranium");
        put("oredict/billet/uranium235", "hbm_m:billet_u235");
        put("oredict/billet/uranium238", "hbm_m:billet_u238");
        put("oredict/billet/zirconium", "hbm_m:billet_zirconium");
        put("oredict/block/aluminum", "hbm_m:block_aluminium", "#forge:storage_blocks/aluminum?");
        put("oredict/block/beryllium", "hbm_m:block_beryllium", "#forge:storage_blocks/beryllium?");
        put("oredict/block/coal", "#forge:storage_blocks/coal");
        put("oredict/block/cobalt", "hbm_m:block_cobalt", "#forge:storage_blocks/cobalt?");
        put("oredict/block/copper", "#forge:storage_blocks/copper", "hbm_m:block_copper");
        put("oredict/block/glass", "#forge:glass", "hbm_m:glass_boron", "hbm_m:glass_lead", "hbm_m:glass_uranium", "hbm_m:glass_trinitite", "hbm_m:glass_polonium", "hbm_m:glass_ash", "#forge:storage_blocks/glass?");
        put("oredict/block/glass_colorless", "#forge:glass/colorless", "#forge:storage_blocks/glass_colorless?");
        put("oredict/block/graphite", "hbm_m:block_graphite", "#forge:storage_blocks/graphite?");
        put("oredict/block/iron", "#forge:storage_blocks/iron");
        put("oredict/block/redstone", "#forge:storage_blocks/redstone");
        put("oredict/block/schrabidium", "hbm_m:block_schrabidium", "#forge:storage_blocks/schrabidium?");
        put("oredict/block/starmetal", "hbm_m:block_starmetal", "#forge:storage_blocks/starmetal?");
        put("oredict/block/steel", "hbm_m:block_steel", "#forge:storage_blocks/steel?");
        put("oredict/block/thorium232", "hbm_m:block_thorium", "#forge:storage_blocks/th232?");
        put("oredict/block/tungsten", "hbm_m:block_tungsten", "#forge:storage_blocks/tungsten?");
        put("oredict/block/uranium238", "hbm_m:block_u238", "#forge:storage_blocks/u238?");
        put("oredict/block/workers_alloy", "hbm_m:block_desh", "#forge:storage_blocks/desh?");
        put("oredict/bolt/dura_steel", "hbm_m:bolt_highspeed_steel");
        put("oredict/bolt/steel", "hbm_m:bolt_steel");
        put("oredict/bolt/tungsten", "hbm_m:bolt_tungsten");
        put("oredict/cobblestone", "#forge:cobblestone");
        put("oredict/crystal/cinnabar", "hbm_m:cinnebar", "hbm_m:crystal_cinnebar");
        put("oredict/dust/aluminum", "hbm_m:aluminum_powder", "#forge:dusts/aluminum?");
        put("oredict/dust/any_plastic", "hbm_m:polymer_powder", "#forge:dusts/polymer?", "hbm_m:bakelite_powder", "#forge:dusts/bakelite?");
        put("oredict/dust/any_smokeless", "hbm_m:ballistite", "hbm_m:cordite", "#forge:dusts/any_smokeless?");
        put("oredict/dust/asbestos", "hbm_m:asbestos_powder", "#forge:dusts/asbestos?");
        put("oredict/dust/astatine", "hbm_m:astatine_powder", "#forge:dusts/astatine?");
        put("oredict/dust/beryllium", "hbm_m:beryllium_powder", "#forge:dusts/beryllium?");
        put("oredict/dust/borax", "hbm_m:borax", "#forge:dusts/borax?");
        put("oredict/dust/boron", "hbm_m:boron_powder", "#forge:dusts/boron?");
        put("oredict/dust/bromine", "hbm_m:bromide_powder", "#forge:dusts/bromine?");
        put("oredict/dust/cadmium", "hbm_m:cadmium_powder", "#forge:dusts/cadmium?");
        put("oredict/dust/caesium", "hbm_m:caesium_powder", "#forge:dusts/caesium?");
        put("oredict/dust/caesium137", "hbm_m:cs137_powder", "#forge:dusts/caesium137?");
        put("oredict/dust/calcium", "hbm_m:calcium_powder", "#forge:dusts/calcium?");
        put("oredict/dust/cerium", "hbm_m:cerium_powder", "#forge:dusts/cerium?");
        put("oredict/dust/coal", "hbm_m:coal_powder", "#forge:dusts/coal?");
        put("oredict/dust/cobalt", "hbm_m:cobalt_powder", "#forge:dusts/cobalt?");
        put("oredict/dust/coltan", "hbm_m:powder_coltan", "hbm_m:coltan_powder", "#forge:dusts/coltan?");
        put("oredict/dust/copper", "hbm_m:copper_powder", "#forge:dusts/copper?");
        put("oredict/dust/diamond", "hbm_m:diamond_powder", "#forge:dusts/diamond?");
        put("oredict/dust/dineutronium", "hbm_m:dineutronium_powder", "#forge:dusts/dineutronium?");
        put("oredict/dust/emerald", "hbm_m:emerald_powder", "#forge:dusts/emerald?");
        put("oredict/dust/euphemium", "hbm_m:euphemium_powder", "#forge:dusts/euphemium?");
        put("oredict/dust/fluorite", "hbm_m:fluorite", "#forge:dusts/fluorite?");
        put("oredict/dust/glowstone", "#forge:dusts/glowstone");
        put("oredict/dust/gold", "hbm_m:gold_powder", "#forge:dusts/gold?");
        put("oredict/dust/iodine", "hbm_m:iodine_powder", "#forge:dusts/iodine?");
        put("oredict/dust/iron", "hbm_m:iron_powder", "#forge:dusts/iron?");
        put("oredict/dust/lanthanum", "hbm_m:lanthanium_powder", "#forge:dusts/lanthanium?");
        put("oredict/dust/lapis", "hbm_m:lapis_powder", "#forge:dusts/lapis?");
        put("oredict/dust/lead", "hbm_m:lead_powder", "#forge:dusts/lead?");
        put("oredict/dust/lignite", "hbm_m:lignite_powder", "#forge:dusts/lignite?");
        put("oredict/dust/limestone", "hbm_m:limestone_powder", "#forge:dusts/limestone?");
        put("oredict/dust/lithium", "hbm_m:lithium_powder", "#forge:dusts/lithium?");
        put("oredict/dust/magnetized_tungsten", "hbm_m:magnetized_tungsten_powder", "#forge:dusts/magnetized_tungsten?");
        put("oredict/dust/mingrade", "hbm_m:red_copper_powder", "#forge:dusts/red_copper?");
        put("oredict/dust/neodymium", "hbm_m:neodymium_powder", "#forge:dusts/neodymium?");
        put("oredict/dust/neptunium237", "hbm_m:neptunium_powder", "#forge:dusts/neptunium?");
        put("oredict/dust/nether_quartz", "hbm_m:quartz_powder", "#forge:dusts/nether_quartz?");
        put("oredict/dust/niobium", "hbm_m:niobium_powder", "#forge:dusts/niobium?");
        put("oredict/dust/plutonium", "hbm_m:plutonium_powder", "#forge:dusts/plutonium?");
        put("oredict/dust/polonium210", "hbm_m:polonium_powder", "#forge:dusts/polonium?");
        put("oredict/dust/red_phosphorus", "hbm_m:fire_powder", "#forge:dusts/phosphorus?");
        put("oredict/dust/redstone", "#forge:dusts/redstone");
        put("oredict/dust/saltpeter", "hbm_m:niter", "#forge:dusts/kno?");
        put("oredict/dust/schrabidium", "hbm_m:schrabidium_powder", "#forge:dusts/schrabidium?");
        put("oredict/dust/sodium", "hbm_m:powder_sodium", "#forge:dusts/sodium?");
        put("oredict/dust/steel", "hbm_m:steel_powder", "#forge:dusts/steel?");
        put("oredict/dust/strontium", "hbm_m:strontium_powder", "#forge:dusts/strontium?");
        put("oredict/dust/sulfur", "hbm_m:sulfur", "#forge:dusts/sulfur?");
        put("oredict/dust/tennessine", "hbm_m:tennessine_powder", "#forge:dusts/tennessine?");
        put("oredict/dust/thorium232", "hbm_m:thorium_powder", "#forge:dusts/th232?");
        put("oredict/dust_tiny/boron", "hbm_m:boron_powder_tiny");
        put("oredict/dust_tiny/cerium", "hbm_m:cerium_powder_tiny");
        put("oredict/dust_tiny/cobalt", "hbm_m:cobalt_powder_tiny");
        put("oredict/dust_tiny/lanthanum", "hbm_m:lanthanium_powder_tiny");
        put("oredict/dust_tiny/lithium", "hbm_m:lithium_powder_tiny");
        put("oredict/dust_tiny/neodymium", "hbm_m:neodymium_powder_tiny");
        put("oredict/dust_tiny/niobium", "hbm_m:niobium_powder_tiny");
        put("oredict/dust/titanium", "hbm_m:titanium_powder", "#forge:dusts/titanium?");
        put("oredict/dust/tungsten", "hbm_m:tungsten_powder", "#forge:dusts/tungsten?");
        put("oredict/dust/uranium", "hbm_m:uranium_powder", "#forge:dusts/uranium?");
        put("oredict/dust/workers_alloy", "hbm_m:desh_powder", "#forge:dusts/desh?");
        put("oredict/dye", "#forge:dyes", "hbm_m:chemical_dye", "hbm_m:crayon", "hbm_m:cinnebar", "hbm_m:sulfur", "hbm_m:coal_powder", "hbm_m:lignite_powder", "hbm_m:titanium_powder", "hbm_m:fluorite", "hbm_m:lapis_powder", "hbm_m:cadmium_powder");
        put("oredict/dye_black", "#forge:dyes/black", "hbm_m:coal_powder", "hbm_m:oil_tar_crude", "hbm_m:oil_tar_crack", "hbm_m:ash_coal", "hbm_m:ash_soot");
        put("oredict/dye_blue", "#forge:dyes/blue", "hbm_m:lapis_powder");
        put("oredict/dye_brown", "#forge:dyes/brown", "hbm_m:lignite_powder", "hbm_m:oil_tar_wood", "hbm_m:ash_fly");
        put("oredict/dye_cyan", "#forge:dyes/cyan", "hbm_m:oil_tar_wax");
        put("oredict/dye_gray", "#forge:dyes/gray", "hbm_m:oil_tar_coal", "hbm_m:ash_misc");
        put("oredict/dye_green", "#forge:dyes/green");
        put("oredict/dye_light_blue", "#forge:dyes/light_blue");
        put("oredict/dye_light_gray", "#forge:dyes/light_gray", "hbm_m:titanium_powder", "hbm_m:ash_wood");
        put("oredict/dye_lime", "#forge:dyes/lime");
        put("oredict/dye_magenta", "#forge:dyes/magenta", "hbm_m:fullerene");
        put("oredict/dye_orange", "#forge:dyes/orange", "hbm_m:cadmium_powder");
        put("oredict/dye_pink", "#forge:dyes/pink");
        put("oredict/dye_purple", "#forge:dyes/purple");
        put("oredict/dye_red", "#forge:dyes/red", "hbm_m:cinnebar");
        put("oredict/dye_white", "#forge:dyes/white", "hbm_m:fluorite", "hbm_m:oil_tar_paraffin");
        put("oredict/dye_yellow", "#forge:dyes/yellow", "hbm_m:sulfur");
        put("oredict/gem/any_coke", "hbm_m:coal_coke", "hbm_m:lignite_coke", "hbm_m:coke_petroleum", "#forge:gems/any_coke?");
        put("oredict/gem/coal", "minecraft:coal", "#forge:gems/coal?");
        put("oredict/gem/diamond", "#forge:gems/diamond");
        put("oredict/gem/emerald", "#forge:gems/emerald");
        put("oredict/gem/lignite", "hbm_m:lignite", "#forge:gems/lignite?");
        put("oredict/gem/nether_quartz", "#forge:gems/quartz", "minecraft:quartz", "#forge:gems/nether_quartz?");
        put("oredict/gem/volcanic", "hbm_m:gem_volcanic", "#forge:gems/volcanic?");
        put("oredict/glyphid_meat", "hbm_m:glyphid_meat", "hbm_m:glyphid_meat_grilled");
        put("oredict/grip/any_plastic", "hbm_m:part_grip_polymer", "hbm_m:part_grip_bakelite");
        put("oredict/gun_mechanism/gun_metal", "hbm_m:part_mechanism_gunmetal");
        put("oredict/gun_mechanism/saturnite", "hbm_m:part_mechanism_saturnite");
        put("oredict/gun_mechanism/weapon_steel", "hbm_m:part_mechanism_weaponsteel");
        put("oredict/ingot/aluminum", "hbm_m:ingot_aluminium", "#forge:ingots/aluminum?");
        put("oredict/ingot/any_bismoid", "hbm_m:bismuth_ingot", "#forge:ingots/bismuth?", "hbm_m:arsenic_ingot", "#forge:ingots/arsenic?");
        put("oredict/ingot/any_bismoid_bronze", "hbm_m:bismuth_bronze_ingot", "#forge:ingots/bismuth_bronze?", "hbm_m:arsenic_bronze_ingot", "#forge:ingots/arsenic_bronze?");
        put("oredict/ingot/any_hard_plastic", "hbm_m:pc_ingot", "#forge:ingots/pc?", "hbm_m:pvc_ingot", "#forge:ingots/pvc?");
        put("oredict/ingot/any_highexplosive", "hbm_m:ball_tnt", "hbm_m:ball_tatb", "#forge:ingots/any_highexplosive?");
        put("oredict/ingot/any_plastic", "hbm_m:polymer_ingot", "#forge:ingots/polymer?", "hbm_m:bakelite_ingot", "#forge:ingots/bakelite?");
        put("oredict/ingot/any_plasticexplosive", "hbm_m:semtex_ingot", "hbm_m:c4_ingot", "#forge:ingots/any_plasticexplosive?");
        put("oredict/ingot/any_resistant_alloy", "hbm_m:tcalloy_ingot", "#forge:ingots/tcalloy?", "hbm_m:cdalloy_ingot", "#forge:ingots/cdalloy?");
        put("oredict/ingot/any_rubber", "hbm_m:biorubber_ingot", "#forge:ingots/latex?", "hbm_m:rubber_ingot", "#forge:ingots/rubber?");
        put("oredict/ingot/arsenic_bronze", "hbm_m:arsenic_bronze_ingot", "#forge:ingots/arsenic_bronze?");
        put("oredict/ingot/asbestos", "hbm_m:asbestos_ingot", "#forge:ingots/asbestos?");
        put("oredict/ingot/australium", "hbm_m:australium_ingot", "#forge:ingots/australium?");
        put("oredict/ingot/beryllium", "hbm_m:beryllium_ingot", "#forge:ingots/beryllium?");
        put("oredict/ingot/bismuth", "hbm_m:bismuth_ingot", "#forge:ingots/bismuth?");
        put("oredict/ingot/bismuth_bronze", "hbm_m:bismuth_bronze_ingot", "#forge:ingots/bismuth_bronze?");
        put("oredict/ingot/boron", "hbm_m:boron_ingot", "#forge:ingots/boron?");
        put("oredict/ingot/brick", "minecraft:brick", "#forge:ingots/brick?");
        put("oredict/ingot/cmb_steel", "hbm_m:combine_steel_ingot", "#forge:ingots/combine_steel?");
        put("oredict/ingot/carbon", "hbm_m:graphite_ingot", "#forge:ingots/carbon?");
        put("oredict/ingot/cobalt", "hbm_m:cobalt_ingot", "#forge:ingots/cobalt?");
        put("oredict/ingot/copper", "#forge:ingots/copper", "minecraft:copper_ingot");
        put("oredict/ingot/desh", "hbm_m:desh_ingot", "#forge:ingots/desh?");
        put("oredict/ingot/dineutronium", "hbm_m:dineutronium_ingot", "#forge:ingots/dineutronium?");
        put("oredict/ingot/dura_steel", "hbm_m:dura_steel_ingot", "hbm_m:ingot_highspeed_steel", "#forge:ingots/dura_steel?");
        put("oredict/ingot/euphemium", "hbm_m:euphemium_ingot", "#forge:ingots/euphemium?");
        put("oredict/ingot/ferrouranium", "hbm_m:ferrouranium_ingot", "#forge:ingots/ferrouranium?");
        put("oredict/ingot/fiberglass", "hbm_m:fiberglass_ingot", "#forge:ingots/fiberglass?");
        put("oredict/ingot/gold", "#forge:ingots/gold");
        put("oredict/ingot/graphite", "hbm_m:graphite_ingot", "#forge:ingots/graphite?");
        put("oredict/ingot/gun_metal", "hbm_m:gunmetal_ingot", "#forge:ingots/gunmetal?");
        put("oredict/ingot/iron", "#forge:ingots/iron");
        put("oredict/ingot/latex", "hbm_m:biorubber_ingot", "#forge:ingots/latex?");
        put("oredict/ingot/lead", "hbm_m:lead_ingot", "#forge:ingots/lead?");
        put("oredict/ingot/lithium", "hbm_m:lithium", "#forge:ingots/lithium?");
        put("oredict/ingot/magnetized_tungsten", "hbm_m:magnetized_tungsten_ingot", "#forge:ingots/magnetized_tungsten?");
        put("oredict/ingot/malachite", "hbm_m:malachite_chunk", "#forge:ingots/malachite?");
        put("oredict/ingot/mingrade", "hbm_m:red_copper_ingot", "#forge:ingots/red_copper?");
        put("oredict/ingot/nether_brick", "minecraft:nether_brick", "#forge:ingots/nether_brick?");
        put("oredict/ingot/niobium", "hbm_m:niobium_ingot", "#forge:ingots/niobium?");
        put("oredict/ingot/osmiridium", "hbm_m:osmiridium_ingot", "#forge:ingots/osmiridium?");
        put("oredict/ingot/redstone", "hbm_m:ingot_redstone", "#forge:ingots/redstone?");
        put("oredict/ingot/rubber", "hbm_m:rubber_ingot", "#forge:ingots/rubber?");
        put("oredict/ingot/saturnite", "hbm_m:saturnite_ingot", "#forge:ingots/saturnite?");
        put("oredict/ingot/schrabidate", "hbm_m:schrabidate_ingot", "#forge:ingots/schrabidate?");
        put("oredict/ingot/schrabidium", "hbm_m:schrabidium_ingot", "#forge:ingots/schrabidium?");
        put("oredict/ingot/schraranium", "hbm_m:schraranium_ingot", "#forge:ingots/schraranium?");
        put("oredict/ingot/silicon", "hbm_m:silicon_ingot", "#forge:ingots/silicon?");
        put("oredict/ingot/starmetal", "hbm_m:starmetal_ingot", "#forge:ingots/starmetal?");
        put("oredict/ingot/steel", "hbm_m:steel_ingot", "#forge:ingots/steel?");
        put("oredict/ingot/tantalum", "hbm_m:tantalium_ingot", "#forge:ingots/tantalium?");
        put("oredict/ingot/thorium232", "hbm_m:th232_ingot", "#forge:ingots/th232?");
        put("oredict/ingot/titanium", "hbm_m:titanium_ingot", "#forge:ingots/titanium?");
        put("oredict/ingot/tungsten", "hbm_m:tungsten_ingot", "#forge:ingots/tungsten?");
        put("oredict/ingot/tungsten_carbide", "hbm_m:ingot_tungsten_carbide", "#forge:ingots/tungsten_carbide?");
        put("oredict/ingot/uranium", "hbm_m:uranium_ingot", "#forge:ingots/uranium?");
        put("oredict/ingot/uranium235", "hbm_m:u235_ingot", "#forge:ingots/u235?");
        put("oredict/ingot/uranium238", "hbm_m:u238_ingot", "#forge:ingots/u238?");
        put("oredict/ingot/weapon_steel", "hbm_m:weaponsteel_ingot", "#forge:ingots/weaponsteel?");
        put("oredict/ingot/white_phosphorus", "hbm_m:phosphorus_ingot", "#forge:ingots/white_phosphorus?");
        put("oredict/ingot/workers_alloy", "hbm_m:desh_ingot", "#forge:ingots/desh?");
        put("oredict/ingot/zirconium", "hbm_m:zirconium_ingot", "#forge:ingots/zirconium?");
        put("oredict/log_wood", "#minecraft:logs", "hbm_m:pink_log");
        put("oredict/ntmchemistryset", "hbm_m:chemistry_set", "hbm_m:chemistry_set_boron");
        put("oredict/ntmpipe/copper", "hbm_m:pipe_copper");
        put("oredict/ntmpipe/dura_steel", "hbm_m:pipe_dura_steel");
        put("oredict/ntmpipe/lead", "hbm_m:pipe_lead");
        put("oredict/ntmpipe/rubber", "hbm_m:pipe_rubber");
        put("oredict/ntmpipe/steel", "hbm_m:pipe_steel");
        put("oredict/nugget/americium241", "hbm_m:nugget_am241", "#forge:nuggets/am241?");
        put("oredict/nugget/americium242", "hbm_m:nugget_am242", "#forge:nuggets/am242?");
        put("oredict/nugget/americium_rg", "hbm_m:nugget_am_mix", "#forge:nuggets/am_mix?");
        put("oredict/nugget/any_bismoid", "hbm_m:nugget_bismuth", "#forge:nuggets/bismuth?", "hbm_m:nugget_arsenic", "#forge:nuggets/arsenic?");
        put("oredict/nugget/beryllium", "hbm_m:nugget_beryllium", "#forge:nuggets/beryllium?");
        put("oredict/nugget/bismuth", "hbm_m:nugget_bismuth", "#forge:nuggets/bismuth?");
        put("oredict/nugget/euphemium", "hbm_m:nugget_euphemium", "#forge:nuggets/euphemium?");
        put("oredict/nugget/gold", "#forge:nuggets/gold");
        put("oredict/nugget/lead", "hbm_m:nugget_lead", "#forge:nuggets/lead?");
        put("oredict/nugget/neptunium237", "hbm_m:nugget_neptunium", "#forge:nuggets/neptunium?");
        put("oredict/nugget/niobium", "hbm_m:nugget_niobium", "hbm_m:fragment_niobium", "#forge:nuggets/niobium?");
        put("oredict/nugget/plutonium238", "hbm_m:nugget_pu238", "#forge:nuggets/pu238?");
        put("oredict/nugget/plutonium239", "hbm_m:nugget_pu239", "#forge:nuggets/pu239?");
        put("oredict/nugget/plutonium240", "hbm_m:nugget_pu240", "#forge:nuggets/pu240?");
        put("oredict/nugget/plutonium241", "hbm_m:nugget_pu241", "#forge:nuggets/pu241?");
        put("oredict/nugget/polonium210", "hbm_m:nugget_polonium", "#forge:nuggets/polonium?");
        put("oredict/nugget/radium226", "hbm_m:nugget_ra226", "#forge:nuggets/ra226?");
        put("oredict/nugget/schrabidium", "hbm_m:nugget_schrabidium", "#forge:nuggets/schrabidium?");
        put("oredict/nugget/silicon", "hbm_m:nugget_silicon", "#forge:nuggets/silicon?");
        put("oredict/nugget/solinium", "hbm_m:nugget_solinium", "#forge:nuggets/solinium?");
        put("oredict/nugget/tantalum", "hbm_m:nugget_tantalium", "#forge:nuggets/tantalium?");
        put("oredict/nugget/technetium99", "hbm_m:nugget_technetium", "#forge:nuggets/technetium?");
        put("oredict/nugget/thorium232", "hbm_m:nugget_th232", "#forge:nuggets/th232?");
        put("oredict/nugget/uranium", "hbm_m:nugget_uranium", "#forge:nuggets/uranium?");
        put("oredict/nugget/uranium233", "hbm_m:nugget_u233", "#forge:nuggets/u233?");
        put("oredict/nugget/uranium235", "hbm_m:nugget_u235", "#forge:nuggets/u235?");
        put("oredict/nugget/uranium238", "hbm_m:nugget_u238", "#forge:nuggets/u238?");
        put("oredict/nugget/zirconium", "hbm_m:nugget_zirconium", "#forge:nuggets/zirconium?");
        put("oredict/ore/aluminum", "hbm_m:ore_aluminium", "#forge:ores/aluminum?");
        put("oredict/ore/beryllium", "hbm_m:beryllium_ore", "#forge:ores/beryllium?");
        put("oredict/ore/copper", "#forge:ores/copper", "hbm_m:ore_copper", "hbm_m:gneiss_copper_ore");
        put("oredict/ore/fluorite", "hbm_m:fluorite_ore", "hbm_m:ore_basalt_fluorite", "#forge:ores/fluorite?");
        put("oredict/ore/iron", "#forge:ores/iron", "hbm_m:gneiss_iron_ore");
        put("oredict/ore/lapis", "#forge:ores/lapis");
        put("oredict/ore/lignite", "hbm_m:lignite_ore", "#forge:ores/lignite?");
        put("oredict/ore/limestone", "hbm_m:stone_resource_limestone", "#forge:ores/limestone?");
        put("oredict/ore_nether/quartz", "minecraft:nether_quartz_ore");
        put("oredict/ore/plutonium", "hbm_m:ore_nether_plutonium", "#forge:ores/plutonium?");
        put("oredict/ore/rare_earth", "hbm_m:ore_rare", "hbm_m:gneiss_rare_ore", "#forge:ores/rare_earth?");
        put("oredict/ore/redstone", "#forge:ores/redstone");
        put("oredict/ore/saltpeter", "hbm_m:niter_ore", "#forge:ores/kno?");
        put("oredict/ore/schrabidium", "hbm_m:schrabidium_ore", "hbm_m:schrabidium_ore_gneiss", "hbm_m:schrabidium_ore_nether", "hbm_m:ore_sellafield_schrabidium", "#forge:ores/schrabidium?");
        put("oredict/ore/uranium", "hbm_m:uranium_ore", "hbm_m:ore_uranium_scorched", "hbm_m:gneiss_uranium_ore", "hbm_m:ore_gneiss_uranium_scorched", "hbm_m:nether_uranium_ore", "hbm_m:ore_nether_uranium_scorched", "hbm_m:ore_sellafield_uranium_scorched", "#forge:ores/uranium?");
        put("oredict/pane_glass", "#forge:glass_panes");
        put("oredict/plank_wood", "#minecraft:planks", "hbm_m:pink_planks");
        put("oredict/plate/aluminum", "hbm_m:plate_aluminium", "#forge:plates/aluminum?");
        put("oredict/plate/cmb_steel", "hbm_m:plate_combine_steel", "#forge:plates/combine_steel?");
        put("oredict/plate/copper", "hbm_m:plate_copper", "#forge:plates/copper?");
        put("oredict/plate/dura_steel", "hbm_m:plate_dura_steel", "#forge:plates/dura_steel?");
        put("oredict/plate/gold", "hbm_m:plate_gold", "#forge:plates/gold?");
        put("oredict/plate/gun_metal", "hbm_m:plate_gunmetal", "#forge:plates/gunmetal?");
        put("oredict/plate/iron", "hbm_m:plate_iron", "#forge:plates/iron?");
        put("oredict/plate/lead", "hbm_m:plate_lead", "#forge:plates/lead?");
        put("oredict/plate/saturnite", "hbm_m:plate_saturnite", "#forge:plates/saturnite?");
        put("oredict/plate/schrabidium", "hbm_m:plate_schrabidium", "#forge:plates/schrabidium?");
        put("oredict/plate_sextuple/aluminum", "hbm_m:plate_welded_aluminium");
        put("oredict/plate_sextuple/any_resistant_alloy", "hbm_m:plate_welded_tcalloy", "hbm_m:plate_welded_cdalloy");
        put("oredict/plate_sextuple/copper", "hbm_m:plate_welded_copper");
        put("oredict/plate_sextuple/steel", "hbm_m:plate_welded_steel");
        put("oredict/plate_sextuple/titanium", "hbm_m:plate_welded_titanium");
        put("oredict/plate_sextuple/tungsten", "hbm_m:plate_welded_tungsten");
        put("oredict/plate_sextuple/zirconium", "hbm_m:plate_welded_zirconium");
        put("oredict/plate/steel", "hbm_m:plate_steel", "#forge:plates/steel?");
        put("oredict/plate/titanium", "hbm_m:plate_titanium", "#forge:plates/titanium?");
        put("oredict/plate_triple/aluminum", "hbm_m:plate_cast_aluminium");
        put("oredict/plate_triple/any_bismoid_bronze", "hbm_m:plate_cast_bbronze", "hbm_m:plate_cast_abronze");
        put("oredict/plate_triple/any_resistant_alloy", "hbm_m:plate_cast_tcalloy", "hbm_m:plate_cast_cdalloy");
        put("oredict/plate_triple/cmb_steel", "hbm_m:plate_cast_cmb");
        put("oredict/plate_triple/copper", "hbm_m:plate_cast_copper");
        put("oredict/plate_triple/dura_steel", "hbm_m:plate_cast_dura_steel");
        put("oredict/plate_triple/ferrouranium", "hbm_m:plate_cast_ferrouranium");
        put("oredict/plate_triple/gold", "hbm_m:plate_cast_gold");
        put("oredict/plate_triple/iron", "hbm_m:plate_cast_iron");
        put("oredict/plate_triple/lead", "hbm_m:plate_cast_lead");
        put("oredict/plate_triple/saturnite", "hbm_m:plate_cast_saturnite");
        put("oredict/plate_triple/steel", "hbm_m:plate_cast_steel");
        put("oredict/plate_triple/titanium", "hbm_m:plate_cast_titanium");
        put("oredict/plate_triple/tungsten", "hbm_m:plate_cast_tungsten");
        put("oredict/plate/weapon_steel", "hbm_m:plate_weaponsteel", "#forge:plates/weaponsteel?");
        put("oredict/sand", "#forge:sand");
        put("oredict/shell/aluminum", "hbm_m:shell_aluminum");
        put("oredict/shell/copper", "hbm_m:shell_copper");
        put("oredict/shell/saturnite", "hbm_m:shell_saturnite");
        put("oredict/shell/steel", "hbm_m:shell_steel");
        put("oredict/shell/titanium", "hbm_m:shell_titanium");
        put("oredict/shell/weapon_steel", "hbm_m:shell_weaponsteel");
        put("oredict/slab_wood", "#minecraft:wooden_slabs", "hbm_m:pink_slab");
        put("oredict/slimeball", "#forge:slimeballs");
        put("oredict/stick_wood", "#forge:rods/wooden");
        put("oredict/stock/any_plastic", "hbm_m:part_stock_polymer", "hbm_m:part_stock_bakelite");
        put("oredict/stone", "#forge:stone");
        put("oredict/tiny/am241", "hbm_m:nugget_am241");
        put("oredict/tiny/am242", "hbm_m:nugget_am242");
        put("oredict/tiny/np237", "hbm_m:nugget_neptunium");
        put("oredict/tiny/pu239", "hbm_m:nugget_pu239");
        put("oredict/tiny/pu240", "hbm_m:nugget_pu240");
        put("oredict/tiny/th232", "hbm_m:nugget_th232");
        put("oredict/tiny/u233", "hbm_m:nugget_u233");
        put("oredict/tiny/u235", "hbm_m:nugget_u235");
        put("oredict/tiny/u238", "hbm_m:nugget_u238");
        put("oredict/tree_leaves", "#minecraft:leaves");
        put("oredict/tree_sapling", "#minecraft:saplings");
        put("oredict/wire_dense/bscco", "hbm_m:wire_dense_bscco");
        put("oredict/wire_dense/copper", "hbm_m:wire_dense_copper");
        put("oredict/wire_dense/gold", "hbm_m:wire_dense_gold");
        put("oredict/wire_dense/magnetized_tungsten", "hbm_m:wire_dense_magnetized_tungsten");
        put("oredict/wire_dense/mingrade", "hbm_m:wire_dense_red_copper");
        put("oredict/wire_dense/neodymium", "hbm_m:wire_dense_neodymium");
        put("oredict/wire_dense/niobium", "hbm_m:wire_dense_niobium");
        put("oredict/wire_dense/schrabidate", "hbm_m:wire_dense_schrabidate");
        put("oredict/wire_dense/starmetal", "hbm_m:wire_dense_star_metal");
        put("oredict/wire_dense/titanium", "hbm_m:wire_dense_titanium");
        put("oredict/wire_fine/aluminum", "hbm_m:wire_aluminium");
        put("oredict/wire_fine/carbon", "hbm_m:wire_carbon");
        put("oredict/wire_fine/copper", "hbm_m:wire_copper");
        put("oredict/wire_fine/gold", "hbm_m:wire_gold");
        put("oredict/wire_fine/lead", "hbm_m:wire_lead");
        put("oredict/wire_fine/magnetized_tungsten", "hbm_m:wire_magnetized_tungsten");
        put("oredict/wire_fine/mingrade", "hbm_m:wire_red_copper");
        put("oredict/wire_fine/schrabidium", "hbm_m:wire_schrabidium");
        put("oredict/wire_fine/steel", "hbm_m:wire_steel");
        put("oredict/wire_fine/tungsten", "hbm_m:wire_tungsten");
        put("oredict/wire_fine/zirconium", "hbm_m:wire_zirconium");
    }
}
//?}
