package com.hbm_m.item.tags_and_tiers;

// Перечисление всех слитков в моде с поддержкой многоязычности.
// Для каждого слитка можно задать переводы на разные языки.

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

public enum ModIngots {
    // Конструктор принимает название и пары "язык, перевод"
    URANIUM("uranium",
            "ru_ru", "Урановый слиток",
            "en_us", "Uranium Ingot"),
    URANIUM233("u233",
            "ru_ru", "Слиток урана-233",
            "en_us", "Uranium-233 Ingot"),
    URANIUM235("u235",
            "ru_ru", "Слиток урана-235",
            "en_us", "Uranium-235 Ingot"),
    URANIUM238("u238",
            "ru_ru", "Слиток урана-238",
            "en_us", "Uranium-238 Ingot"),
    THORIUM232("th232",
            "ru_ru", "Слиток тория-232",
            "en_us", "Thorium-232 Ingot"),
    PLUTONIUM("plutonium",
            "ru_ru", "Плутониевый слиток",
            "en_us", "Plutonium Ingot"),
    PLUTONIUM238("pu238",
            "ru_ru", "Слиток плутония-238",
            "en_us", "Plutonium-238 Ingot"),
    PLUTONIUM239("pu239",
            "ru_ru", "Слиток плутония-239",
            "en_us", "Plutonium-239 Ingot"),
    PLUTONIUM240("pu240",
            "ru_ru", "Слиток плутония-240",
            "en_us", "Plutonium-240 Ingot"),
    PLUTONIUM241("pu241",
            "ru_ru", "Слиток плутония-241",
            "en_us", "Plutonium-241 Ingot"),
    ACTINIUM("actinium",
            "ru_ru", "Слиток актиния-227",
            "en_us", "Actinium-227 Ingot"),
    STEEL("steel",
            "ru_ru", "Стальной слиток",
            "en_us", "Steel Ingot"),
    ADVANCED_ALLOY("advanced_alloy",
            "ru_ru", "Слиток продвинутого сплава",
            "en_us", "Advanced Alloy Ingot"),
    ALUMINUM("aluminum",
            "ru_ru", "Слиток алюминия",
            "en_us", "Aluminium Ingot"),
    SCHRABIDIUM("schrabidium",
            "ru_ru", "Шрабидиевый слиток",
            "en_us", "Schrabidium Ingot"),
    SATURNITE("saturnite",
            "ru_ru", "Сатурнитовый слиток",
            "en_us", "Saturnite Ingot"),
    LEAD("lead",
            "ru_ru", "Свинцовый слиток",
            "en_us", "Lead Ingot"),
    GUNMETAL("gunmetal",
            "ru_ru", "Слиток пушечной бронзы",
            "en_us", "Gunmetal Ingot"),
    GUNSTEEL("gunsteel",
            "ru_ru", "Слиток оружейной стали",
            "en_us", "Gunsteel Ingot"),
    WEAPONSTEEL("weaponsteel",
            "ru_ru", "Слиток боевой стали",
            "en_us", "Weapon Steel Ingot"),
    RED_COPPER("red_copper",
            "ru_ru", "Слиток красной меди",
            "en_us", "Minecraft Grade Copper Ingot"),
    ASBESTOS("asbestos",
            "ru_ru", "Асбестовый лист",
            "en_us", "Asbestos Sheet"),
    TITANIUM("titanium",
            "ru_ru", "Титановый слиток",
            "en_us", "Titanium Ingot"),
    COBALT("cobalt",
            "ru_ru", "Кобальтовый слиток",
            "en_us", "Cobalt Ingot"),
    TUNGSTEN("tungsten",
            "ru_ru", "Вольфрамовый слиток",
            "en_us", "Tungsten Ingot"),
    STARMETAL("starmetal",
            "ru_ru", "§9Звёздный металл§r",
            "en_us", "§9Starmetal Ingot§r"),
    BERYLLIUM("beryllium",
            "ru_ru", "Бериллиевый слиток",
            "en_us", "Beryllium Ingot"),
    BISMUTH("bismuth",
            "ru_ru", "Слиток висмута",
            "en_us", "Bismuth Ingot"),
    POLYMER("polymer",
            "ru_ru", "Брусок полимера",
            "en_us", "Polymer Bar"),
    BAKELITE("bakelite",
            "ru_ru", "Брусок бакелита",
            "en_us", "Bakelite Bar"),
    RUBBER("rubber",
            "ru_ru", "Брусок резины",
            "en_us", "Rubber Bar"),
    DESH("desh",
            "ru_ru", "Деш-слиток",
            "en_us", "Desh Ingot"),
    GRAPHITE("graphite",
            "ru_ru", "Графитовый слиток",
            "en_us", "Graphite Ingot"),
    PHOSPHORUS("phosphorus",
            "ru_ru", "Брусок белого фосфора",
            "en_us", "Bar of White Phosphorus"),
    LITHIUM_INGOT("les",
            "ru_ru", "Куб лития",
            "en_us", "Lithium Cube"),
    MAGNETIZED_TUNGSTEN("magnetized_tungsten",
            "ru_ru", "Слиток намагниченного вольфрама",
            "en_us", "Magnetized Tungsten Ingot"),
    COMBINE_STEEL("combine_steel",
            "ru_ru", "Слиток Стали Альянса",
            "en_us", "CMB Steel Ingot"),
    DURA_STEEL("dura_steel",
            "ru_ru", "Слиток быстрорежущей стали",
            "en_us", "High-Speed Steel Ingot"),
    POLYMER_COMPOSITE("pc",
            "ru_ru", "Брусок твёрдого пластика",
            "en_us", "Hard Plastic Bar"),
    DIGAMMA("digamma",
            "ru_ru", "Слиток Дигаммы",
            "en_us", "Digamma Ingot"),
    EUPHEMIUM("euphemium",
            "ru_ru", "Эвфемиевый слиток",
            "en_us", "Euphemium Ingot"),
    DINEUTRONIUM("dineutronium",
            "ru_ru", "Динейтрониевый слиток",
            "en_us", "Dineutronium Ingot"),
    ELECTRONIUM("electronium",
            "ru_ru", "Электрониевый слиток",
            "en_us", "Electronium Ingot"),
    AUSTRALIUM("australium",
            "ru_ru", "Австралиевый слиток",
            "en_us", "Australium Ingot"),
    SOLINIUM("solinium",
            "ru_ru", "Солиниевый слиток",
            "en_us", "Solinium Ingot"),
    TANTALIUM("tantalium",
            "ru_ru", "Танталовый слиток",
            "en_us", "Tantalum Ingot"),
    CHAINSSTEEL("chainsteel",
            "ru_ru", "Тяжёлая цепная сталь",
            "en_us", "Heavy Chainsteel"),
    METEORITE("meteorite",
            "ru_ru", "Метеоритовый слиток",
            "en_us", "Meteorite Ingot"),
    LANTHANIUM("lanthanium",
            "ru_ru", "Полустабильный слиток лантана",
            "en_us", "Semi-Stable Lanthanium Ingot"),
    NEODYMIUM("neodymium",
            "ru_ru", "Неодимовый слиток",
            "en_us", "Neodymium Ingot"),
    NIOBIUM("niobium",
            "ru_ru", "Ниобиевый слиток",
            "en_us", "Niobium Ingot"),
    CERIUM("cerium",
            "ru_ru", "Цериевый слиток",
            "en_us", "Cerium Ingot"),
    CADMIUM("cadmium",
            "ru_ru", "Кадмиевый слиток",
            "en_us", "Cadmium Ingot"),
    CAESIUM("caesium",
            "ru_ru", "Цезиевый слиток",
            "en_us", "Caesium Ingot"),
    STRONTIUM("strontium",
            "ru_ru", "Стронциевый слиток",
            "en_us", "Strontium Ingot"),
    BROMINE("bromide",
            "ru_ru", "Слиток бромида",
            "en_us", "Bromide Ingot"),
    TENNESSINE("tennessine",
            "ru_ru", "Теннессиевый слиток",
            "en_us", "Tennessine Ingot"),
    ZIRCONIUM("zirconium",
            "ru_ru", "Циркониевый куб",
            "en_us", "Zirconium Cube"),
    ARSENIC("arsenic",
            "ru_ru", "Слиток мышьяка",
            "en_us", "Arsenic Ingot"),
    IODINE("iodine",
            "ru_ru", "Йодный слиток",
            "en_us", "Iodine Ingot"),
    ASTATINE("astatine",
            "ru_ru", "Астатовый слиток",
            "en_us", "Astatine Ingot"),
    AMERICIUM("americium",
            "ru_ru", "Америциевый слиток",
            "en_us", "Americium Ingot"),
    NEPTUNIUM("neptunium",
            "ru_ru", "Нептуниевый слиток",
            "en_us", "Neptunium Ingot"),
    POLONIUM("polonium",
            "ru_ru", "Слиток полония-210",
            "en_us", "Polonium-210 Ingot"),
    TECHNETIUM("technetium",
            "ru_ru", "Слиток технеция-99",
            "en_us", "Technetium-99 Ingot"),
    BORON("boron",
            "ru_ru", "Борный слиток",
            "en_us", "Boron Ingot"),
    SCHRABIDATE("schrabidate",
            "ru_ru", "Слиток шрабидата железа",
            "en_us", "Ferric Schrabidate Ingot"),
    SCHRARANIUM("schraranium",
            "ru_ru", "Шрараниевый слиток",
            "en_us", "Schraranium Ingot"),
    AU198("au198",
            "ru_ru", "Слиток золота-198",
            "en_us", "Gold-198 Ingot"),
    PB209("pb209",
            "ru_ru", "Слиток свинца-209",
            "en_us", "Lead-209 Ingot"),
    RA226("ra226",
            "ru_ru", "Слиток радия-226",
            "en_us", "Radium-226 Ingot"),
    THORIUM("thorium",
            "ru_ru", "Ториевый слиток",
            "en_us", "Thorium Ingot"),
    OSMIRIDIUM("osmiridium",
            "ru_ru", "Осмиридиевый слиток",
            "en_us", "Osmiridium Ingot"),
    SELENIUM("selenium",
            "ru_ru", "Селениевый слиток",
            "en_us", "Selenium Ingot"),
    CO60("co60",
            "ru_ru", "Слиток кобальта-60",
            "en_us", "Cobalt-60 Ingot"),
    SR90("sr90",
            "ru_ru", "Слиток стронция-90",
            "en_us", "Strontium-90 Ingot"),
    AM241("am241",
            "ru_ru", "Слиток америция-241",
            "en_us", "Americium-241 Ingot"),
    AM242("am242",
            "ru_ru", "Слиток америция-242",
            "en_us", "Americium-242 Ingot"),
    STEEL_DUSTED("steel_dusted",
            "ru_ru", "Запылённый стальной слиток",
            "en_us", "Dusted Steel Ingot"),
    CALCIUM("calcium",
            "ru_ru", "Кальциевый слиток",
            "en_us", "Calcium Ingot"),
    GRAPHENE("graphene",
            "ru_ru", "Графеновый лист",
            "en_us", "Graphene Sheet"),
    MOX_FUEL("mox_fuel",
            "ru_ru", "Слиток МОКС-топлива",
            "en_us", "Ingot of MOX Fuel"),
    SMORE("smore",
            "ru_ru", "Слиток с'мора",
            "en_us", "S'more Ingot"),
    SCHRABIDIUM_FUEL("schrabidium_fuel",
            "ru_ru", "Слиток шрабидиевого топлива",
            "en_us", "Ingot of Schrabidium Fuel"),
    URANIUM_FUEL("uranium_fuel",
            "ru_ru", "Слиток уранового топлива",
            "en_us", "Ingot of Uranium Fuel"),
    THORIUM_FUEL("thorium_fuel",
            "ru_ru", "Слиток ториевого топлива",
            "en_us", "Ingot of Thorium Fuel"),
    PLUTONIUM_FUEL("plutonium_fuel",
            "ru_ru", "Слиток плутониевого топлива",
            "en_us", "Ingot of Plutonium Fuel"),
    NEPTUNIUM_FUEL("neptunium_fuel",
            "ru_ru", "Слиток нептуниевого топлива",
            "en_us", "Ingot of Neptunium Fuel"),
    AMERICIUM_FUEL("americium_fuel",
            "ru_ru", "Слиток америциевого топлива",
            "en_us", "Ingot of Americium Fuel"),
    BISMUTH_BRONZE("bismuth_bronze",
            "ru_ru", "Слиток висмутовой бронзы",
            "en_us", "Bismuth Bronze Ingot"),
    ARSENIC_BRONZE("arsenic_bronze",
            "ru_ru", "Слиток мышьяковой бронзы",
            "en_us", "Arsenic Bronze Ingot"),
    CRYSTALLINE("crystalline",
            "ru_ru", "Кристаллиниевый слиток",
            "en_us", "Crystalline Ingot"),
    MUD("mud",
            "ru_ru", "Кирпич из твёрдых отходов",
            "en_us", "Solid Mud Brick"),
    SILICON("silicon",
            "ru_ru", "Брусок кремния",
            "en_us", "Silicon Boule"),
    FIBERGLASS("fiberglass",
            "ru_ru", "Брусок стекловолокна",
            "en_us", "Fiberglass Bar"),
    CERAMIC("ceramic",
            "ru_ru", "Керамический слиток",
            "en_us", "Ceramic Ingot"),
    PU_MIX("pu_mix",
            "ru_ru", "Слиток плутония реакторного качества",
            "en_us", "Reactor Grade Plutonium Ingot"),
    AM_MIX("am_mix",
            "ru_ru", "Слиток америция реакторного качества",
            "en_us", "Reactor Grade Americium Ingot"),
    PET("pet",
            "ru_ru", "ПЭТ слиток",
            "en_us", "PET Ingot"),
    FERROURANIUM("ferrouranium",
            "ru_ru", "Ферроурановый слиток",
            "en_us", "Ferrouranium Ingot"),
    PVC("pvc",
            "ru_ru", "Брусок ПВХ",
            "en_us", "PVC Bar"),
    BIORUBBER("biorubber",
            "ru_ru", "Брусок латекса",
            "en_us", "Latex Bar"),
    SEMTEX("semtex",
            "ru_ru", "Брусок семтекса",
            "en_us", "Bar of Semtex"),
    C4("c4",
            "ru_ru", "Брусок C-4",
            "en_us", "Bar of Composition C-4"),
    STABALLOY("staballoy",
            "ru_ru", "Стабаллой",
            "en_us", "Staballoy"),
    METAL_SCRAP("metal.scrap",
            "ru_ru", "Металлолом",
            "en_us", "Metal Scrap"),
    METEORITE_FORGED("meteorite_forged",
            "ru_ru", "Выкованный метеоритовый слиток",
            "en_us", "Forged Meteorite Ingot"),
    METEORITE_FORGED_HOT("meteorite_forged_hot",
            "ru_ru", "Горячий кованый метеоритный слиток",
            "en_us", "Hot Forged Meteorite Ingot"),
    METEORITE_HOT("meteorite_hot",
            "ru_ru", "Горячий метеоритный слиток",
            "en_us", "Hot Meteorite Ingot"),
    IRON_SMALL("iron_small",
            "ru_ru", "Маленький железный слиток",
            "en_us", "Small Iron Ingot"),
    CHAINSTEEL_HOT("chainsteel_hot",
            "ru_ru", "Горячая цепная сталь",
            "en_us", "Hot Chain Steel"),
    STARMETAL_ORION_BASE("starmetal_orion_base",
            "ru_ru", "Базовый звёздный металл Орион",
            "en_us", "Star Metal Orion Base"),
    STARMETAL_ORION("starmetal_orion",
            "ru_ru", "Звёздный металл Орион",
            "en_us", "Star Metal Orion"),
    STARMETAL_URSA_BASE("starmetal_ursa_base",
            "ru_ru", "Базовый звёздный металл Урса",
            "en_us", "Star Metal Ursa Base"),
    STARMETAL_URSA("starmetal_ursa",
            "ru_ru", "Звёздный металл Урса",
            "en_us", "Star Metal Ursa"),
    STARMETAL_ASTRA_BASE("starmetal_astra_base",
            "ru_ru", "Базовый звёздный металл Астра",
            "en_us", "Star Metal Astra Base"),
    STARMETAL_ASTRA("starmetal_astra",
            "ru_ru", "Звёздный металл Астра",
            "en_us", "Star Metal Astra"),
    DESH_RAINBOW("desh_rainbow",
            "ru_ru", "Ненавижу пони.",
            "en_us", "Rainbow Desh"),
    TCALLOY("tcalloy",
            "ru_ru", "Слиток технециевой стали",
            "en_us", "Technetium Steel Ingot"),
    U238M2("u238m2",
            "ru_ru", "Слиток метастабильного урана-238M2",
            "en_us", "Metastable Uranium-238M2 Ingot"),
    CELNEUTRONOPHYRIUM_NEW("celneutronophyrium_new",
            "ru_ru", "Новый цельнейтронофириевый слиток",
            "en_us", "New Celneutronophyrium Ingot"),
    CELNEUTRONOPHYRIUM("celneutronophyrium",
            "ru_ru", "Цельнейтронофириевый слиток",
            "en_us", "Celneutronophyrium Ingot"),
    TETRANEUTRONIUM_NEW("tetraneutronium_new",
            "ru_ru", "Новый тетранейтрониевый слиток",
            "en_us", "New Tetraneutronium Ingot"),
    TETRANEUTRONIUM("tetraneutronium",
            "ru_ru", "Тетранейтрониевый слиток",
            "en_us", "Tetraneutronium Ingot"),
    CFT("cft",
            "ru_ru", "Кристаллический фуллерит",
            "en_us", "Crystalline Fullerite"),
    CDALLOY("cdalloy",
            "ru_ru", "Слиток кадмиевой стали",
            "en_us", "Cadmium Steel Ingot"),
    BSCCO("bscco",
            "ru_ru", "Слиток BSCCO",
            "en_us", "BSCCO Ingot"),
    BESKAR_DOUBLE("beskar_double",
            "ru_ru", "Двойной бескаровый слиток",
            "en_us", "Double Beskar Ingot"),
    BESKAR("beskar",
            "ru_ru", "Бескаровый слиток",
            "en_us", "Beskar Ingot");

    private final String name;
    private final Map<String, String> translations;
    private static final Map<String, ModIngots> BY_NAME = new HashMap<>();

    /**
     * Конструктор для слитков с поддержкой нескольких языков.
     * @param name Системное имя (например, "uranium")
     * @param translationPairs Пары строк: "код_языка", "перевод". Например: "ru_ru", "Слиток", "en_us", "Ingot"
     */
    ModIngots(String name, String... translationPairs) {
        this.name = name;
        
        if (translationPairs.length % 2 != 0) {
            throw new IllegalArgumentException("Translation pairs must be even for ingot: " + name);
        }

        Map<String, String> translationMap = new HashMap<>();
        for (int i = 0; i < translationPairs.length; i += 2) {
            String locale = translationPairs[i];
            String translation = translationPairs[i + 1];
            translationMap.put(locale, translation);
        }
        this.translations = Collections.unmodifiableMap(translationMap);
    }

    static {
        for (ModIngots ingot : values()) {
            BY_NAME.put(ingot.name, ingot);
        }
    }

    public String getName() {
        return name;
    }

    /**
     * Получает перевод для указанного языка.
     * @param locale Код языка (например, "ru_ru").
     * @return Перевод или null, если он не найден.
     */
    public String getTranslation(String locale) {
        return translations.get(locale);
    }

    public static Optional<ModIngots> byName(String name) {
        return Optional.ofNullable(BY_NAME.get(name));
    }
}