//Schematic to java Structure by jajo_11 | inspired by "MITHION'S.SCHEMATIC TO JAVA CONVERTINGTOOL"

package com.hbm_m.world.dungeon;

import java.util.Arrays;
import java.util.List;
import java.util.Random;

import com.hbm_m.config.GeneralConfig;
import com.hbm_m.itempool.ItemPool;
import com.hbm_m.main.MainRegistry;
import com.hbm_m.itempool.ItemPoolsComponent;
import com.hbm_m.itempool.ItemPoolsLegacy;
import com.hbm_m.itempool.ItemPoolsSingle;
import com.hbm_m.itempool.ItemPoolsPile;
import com.hbm_m.world.gen.legacy.L;
import com.hbm_m.world.gen.legacy.LB;
import com.hbm_m.world.gen.legacy.LMaterial;
import com.hbm_m.world.gen.legacy.MB;
import com.hbm_m.world.gen.legacy.MetaBlock;
import com.hbm_m.world.generator.DungeonToolbox;
import com.hbm_m.util.Vec3NT;
import com.hbm_m.world.gen.legacy.VB;

import net.minecraft.world.Container;
import net.minecraft.world.level.LevelAccessor;





/**
 * 1:1 {@code com.hbm.world.dungeon.Spaceship2} (Original-Weltgen-Klasse, zeilengetreu auf die Port-Hilfen {@code L}/{@code MB}/{@code VB} umgesetzt).
 */
public class Spaceship2
{
	LB Block1 = MB.deco_tungsten;
	LB Block2 = MB.hadron_coil_alloy;
	LB Block3 = MB.deco_steel;
	LB Block4 = MB.fusion_heater;
	LB Block5 = MB.block_meteor;
	LB Block6 = MB.pwr_fuel;
	LB Block8 = MB.fusion_hatch;
	LB Block9 = MB.reinforced_light;
	LB Block10 = MB.reinforced_glass;
	
	public boolean generate_r00(LevelAccessor world, Random rand, int x, int y, int z)
    {
		L.setBlock(world, x + 9, y + 0, z + 17, VB.air, 0, 3);
		L.setBlock(world, x + 10, y + 0, z + 17, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 0, z + 18, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 0, z + 18, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 18, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 18, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 18, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 18, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 18, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 18, VB.air, 0, 3);
		L.setBlock(world, x + 10, y + 0, z + 18, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 0, z + 19, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 0, z + 19, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 19, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 19, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 19, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 19, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 19, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 19, VB.air, 0, 3);
		L.setBlock(world, x + 10, y + 0, z + 19, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 0, z + 20, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 0, z + 20, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 20, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 20, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 20, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 20, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 20, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 20, VB.air, 0, 3);
		L.setBlock(world, x + 10, y + 0, z + 20, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 0, z + 21, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 0, z + 21, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 21, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 21, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 21, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 21, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 21, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 21, VB.air, 0, 3);
		L.setBlock(world, x + 10, y + 0, z + 21, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 0, z + 22, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 0, z + 22, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 22, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 22, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 22, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 22, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 22, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 22, VB.air, 0, 3);
		L.setBlock(world, x + 10, y + 0, z + 22, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 0, z + 23, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 0, z + 23, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 23, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 23, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 23, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 23, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 23, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 23, VB.air, 0, 3);
		L.setBlock(world, x + 10, y + 0, z + 23, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 0, z + 24, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 0, z + 24, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 24, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 24, Block3, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 24, Block3, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 24, Block3, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 24, Block3, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 24, VB.air, 0, 3);
		L.setBlock(world, x + 10, y + 0, z + 24, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 0, z + 25, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 0, z + 25, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 25, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 25, Block3, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 25, Block3, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 25, Block3, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 25, Block3, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 25, VB.air, 0, 3);
		L.setBlock(world, x + 10, y + 0, z + 25, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 0, z + 26, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 0, z + 26, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 26, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 26, Block3, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 26, Block3, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 26, Block3, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 26, Block3, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 26, VB.air, 0, 3);
		L.setBlock(world, x + 10, y + 0, z + 26, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 0, z + 27, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 0, z + 27, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 27, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 27, Block3, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 27, Block3, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 27, Block3, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 27, Block3, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 27, VB.air, 0, 3);
		L.setBlock(world, x + 10, y + 0, z + 27, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 0, z + 28, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 0, z + 28, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 28, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 28, Block3, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 28, Block3, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 28, Block3, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 28, Block3, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 28, VB.air, 0, 3);
		L.setBlock(world, x + 10, y + 0, z + 28, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 0, z + 29, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 0, z + 29, Block3, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 29, Block3, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 29, Block3, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 29, Block3, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 29, Block3, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 29, Block3, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 29, Block3, 0, 3);
		L.setBlock(world, x + 10, y + 0, z + 29, Block3, 0, 3);
		L.setBlock(world, x + 2, y + 0, z + 30, Block3, 0, 3);
		L.setBlock(world, x + 3, y + 0, z + 30, Block3, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 30, Block3, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 30, Block3, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 30, Block3, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 30, Block3, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 30, Block3, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 30, Block3, 0, 3);
		L.setBlock(world, x + 10, y + 0, z + 30, Block3, 0, 3);
		L.setBlock(world, x + 11, y + 0, z + 30, Block3, 0, 3);
		L.setBlock(world, x + 3, y + 0, z + 31, Block3, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 31, Block3, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 31, Block3, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 31, Block3, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 31, Block3, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 31, Block3, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 31, Block3, 0, 3);
		L.setBlock(world, x + 10, y + 0, z + 31, Block3, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 32, Block3, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 32, Block3, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 32, Block3, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 32, Block3, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 33, Block3, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 33, Block3, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 33, Block3, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 33, Block3, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 34, Block3, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 34, Block3, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 34, Block3, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 34, Block3, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 35, Block3, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 35, Block3, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 35, Block3, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 35, Block3, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 36, Block3, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 36, Block3, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 36, Block3, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 36, Block3, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 37, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 37, Block3, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 37, Block3, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 37, Block3, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 37, Block3, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 38, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 38, Block3, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 38, Block3, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 38, Block3, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 38, Block3, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 38, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 39, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 39, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 39, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 39, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 39, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 39, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 40, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 40, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 40, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 40, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 40, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 41, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 41, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 41, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 42, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 42, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 42, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 42, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 0, z + 43, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 43, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 43, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 43, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 43, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 43, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 44, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 44, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 44, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 44, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 0, z + 44, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 0, z + 45, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 0, z + 45, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 0, z + 45, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 0, z + 45, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 1, z + 2, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 1, z + 3, VB.air, 0, 3);
		L.setBlock(world, x + 11, y + 1, z + 3, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 1, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 1, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 1, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 10, y + 1, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 11, y + 1, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 2, y + 1, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 1, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 1, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 1, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 10, y + 1, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 11, y + 1, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 1, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 1, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 1, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 10, y + 1, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 1, z + 7, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 1, z + 7, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 1, z + 7, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 7, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 7, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 1, z + 7, VB.air, 0, 3);
		L.setBlock(world, x + 3, y + 1, z + 8, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 1, z + 8, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 1, z + 8, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 8, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 8, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 8, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 1, z + 8, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 1, z + 9, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 1, z + 9, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 9, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 9, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 9, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 1, z + 9, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 1, z + 10, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 1, z + 10, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 10, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 10, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 10, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 1, z + 10, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 1, z + 11, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 1, z + 11, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 11, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 11, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 11, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 1, z + 11, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 1, z + 12, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 1, z + 12, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 12, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 12, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 12, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 1, z + 12, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 1, z + 13, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 1, z + 13, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 13, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 13, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 13, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 1, z + 13, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 1, z + 14, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 1, z + 14, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 14, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 14, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 14, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 1, z + 14, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 1, z + 15, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 1, z + 15, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 15, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 15, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 15, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 1, z + 15, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 1, z + 16, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 16, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 16, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 16, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 1, z + 16, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 1, z + 17, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 17, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 17, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 17, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 1, z + 18, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 18, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 18, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 18, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 1, z + 19, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 19, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 19, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 19, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 1, z + 20, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 20, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 20, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 20, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 21, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 21, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 22, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 41, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 42, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 42, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 43, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 43, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 43, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 44, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 1, z + 44, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 1, z + 44, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 1, z + 45, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 2, z + 1, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 2, z + 1, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 2, z + 2, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 2, z + 2, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 2, z + 3, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 2, z + 3, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 2, z + 3, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 2, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 2, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 2, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 2, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 2, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 2, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 2, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 2, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 2, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 2, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 2, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 2, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 2, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 2, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 9, y + 2, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 4, y + 2, z + 7, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 2, z + 7, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 2, z + 7, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 2, z + 7, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 2, z + 7, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 2, z + 8, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 2, z + 8, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 2, z + 8, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 2, z + 8, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 2, z + 9, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 2, z + 9, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 2, z + 9, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 2, z + 9, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 2, z + 10, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 2, z + 10, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 2, z + 10, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 2, z + 10, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 2, z + 11, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 2, z + 11, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 2, z + 11, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 2, z + 11, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 2, z + 12, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 2, z + 12, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 2, z + 12, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 2, z + 12, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 2, z + 13, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 2, z + 13, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 2, z + 13, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 2, z + 13, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 2, z + 14, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 2, z + 14, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 2, z + 14, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 2, z + 14, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 2, z + 15, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 2, z + 15, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 2, z + 15, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 2, z + 16, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 3, z + 2, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 3, z + 2, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 3, z + 3, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 3, z + 3, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 3, z + 3, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 3, z + 3, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 3, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 3, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 3, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 3, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 3, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 3, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 3, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 3, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 3, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 3, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 3, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 3, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 3, z + 7, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 3, z + 7, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 3, z + 7, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 3, z + 7, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 3, z + 8, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 3, z + 8, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 3, z + 8, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 3, z + 8, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 3, z + 9, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 3, z + 9, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 3, z + 9, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 3, z + 9, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 3, z + 10, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 3, z + 10, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 3, z + 10, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 3, z + 10, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 3, z + 11, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 3, z + 11, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 3, z + 11, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 3, z + 12, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 4, z + 0, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 4, z + 1, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 4, z + 1, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 4, z + 1, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 4, z + 2, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 4, z + 2, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 4, z + 2, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 4, z + 2, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 4, z + 3, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 4, z + 3, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 4, z + 3, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 4, z + 3, VB.air, 0, 3);
		L.setBlock(world, x + 5, y + 4, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 4, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 4, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 4, z + 4, VB.air, 0, 3);
		L.setBlock(world, x + 6, y + 4, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 4, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 4, z + 5, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 4, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 8, y + 4, z + 6, VB.air, 0, 3);
		L.setBlock(world, x + 7, y + 4, z + 7, VB.air, 0, 3);
		if(GeneralConfig.enableDebugMode)
			System.out.print("[Debug] Successfully spawned spaceship at " + x + " " + y +" " + z + "\n");
		return true;

	}

}