package com.hbm_m.item.machine;

import com.hbm_m.item.ModItems;

import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.level.Level;

import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.List;
import java.util.function.Supplier;

/**
 * 1:1-Port von {@code ItemRTGPellet} (1.7.10): die Waermequelle eines Radioisotopengenerators.
 *
 * <p>Jedes Pellet hat eine feste Heizleistung und - bis auf wenige Ausnahmen - eine
 * <b>Lebensdauer</b>. Die ist aus der echten Halbwertszeit gerechnet
 * ({@link #lifespan(float, HalfLifeType)}), mal anderthalb. Ein Radiumpellet haelt damit
 * jahrelang und heizt kaum, ein Bleipellet ist in Minuten durch und heizt zweihundertfach - das
 * ist die eigentliche Entscheidung beim Bau eines RTG.</p>
 *
 * <p>Ist die Lebensdauer aufgebraucht, wird das Pellet zu seinem <b>Zerfallsprodukt</b>: Radium zu
 * Blei, Strontium zu Zirconium, Cobalt zu Nickel. Solange {@link #scalePower} gilt, sinkt die
 * Heizleistung dabei mit der Restlaufzeit, statt bis zuletzt voll zu bleiben.</p>
 *
 * <p><b>Anmerkung:</b> Heizleistung und Zerfall haengen wie im Original an zwei Konfigurationsschaltern
 * ({@code VersatileConfig.rtgDecay}, {@code scaleRTGPower}; Vorgabe: Zerfall an, Skalierung aus).</p>
 */
public class ItemRTGPellet extends Item {

    /** Alle angemeldeten Pellets - das Original fuehrt dieselbe Liste fuer die Rezeptanzeige. */
    public static final List<ItemRTGPellet> PELLETS = new ArrayList<>();

    /** Original: {@code PELLET_DEPLETION}. */
    public static final String KEY_DEPLETION = "PELLET_DEPLETION";

    // Restport: rtgDecay/scaleRTGPower kommen aus VersatileConfig (MachineConfig 9.00/9.01, 528-Modus).

    /** Original: {@code HalfLifeType} - in welchen Einheiten die Halbwertszeit angegeben ist. */
    public enum HalfLifeType { SHORT, MEDIUM, LONG }

    private final short heat;
    private final long lifespan;
    @Nullable
    private final Supplier<Item> decayItem;

    /** Ein Pellet ohne Zerfall - es haelt ewig. */
    public ItemRTGPellet(int heat, Properties properties) {
        this(heat, 0L, null, properties);
    }

    public ItemRTGPellet(int heat, long lifespan, @Nullable Supplier<Item> decayItem, Properties properties) {
        super(properties.stacksTo(1));
        this.heat = (short) heat;
        this.lifespan = lifespan;
        this.decayItem = decayItem;
        PELLETS.add(this);
    }

    /**
     * 1:1-Port von {@code RTGUtil.getLifespan}: aus der Halbwertszeit werden Ticks.
     *
     * <p>Ein Minecraftjahr sind hier hundert Tage zu je 48000 Ticks - das Original rechnet
     * ausdruecklich nicht mit echten 365.</p>
     */
    public static long lifespan(float halfLife, HalfLifeType type) {
        return switch (type) {
            case LONG -> (long) ((48000L * 100L * 100L) * halfLife);
            case MEDIUM -> (long) ((48000L * 100L) * halfLife);
            case SHORT -> (long) (48000L * halfLife);
        };
    }

    /** Dasselbe mal anderthalb - so steht es an jeder Pelletzeile des Originals. */
    public static long lifespan15(float halfLife, HalfLifeType type) {
        return (long) (lifespan(halfLife, type) * 1.5D);
    }

    private static final String[] facts = new String[] {
            "One gram of Pu-238 costs $8,000.",
            "One gram of Pu-238 produces just under half a Watt of decay heat.",
            "The typical plutonium RTG contains close to eight kilograms of Pu-238.",
            "Pu-238's half life is 87.7 years.",
            "A plutonium RTG was used to power the New Horizons probe that visited Pluto in 2015.",
            "Po-210 can also be used for RTGs as it generates 140 W/g of decay heat due to its 138 day half life.",
            "Pa-231 is an isotope of protactinium that easily fissions, but it isn't quite fissile.",
            "Muons generated by matter-antimatter reactions can trigger nuclear fusion reactions at room temperature.",
            "Roughly 20% of U-235 nuclei will fail to fission when hit by a neutron. They become U-236 nuclei instead.",
            "Thorium reactors are really uranium reactors that convert thorium into U-233.",
            "Natural uranium consists of 99.284% U-238, 0.711% U-235, and 0.0055% U-234.",
            "Most nuclear reactors use uranium that has been enriched to 3-5% U-235.",
            "Uranium-based nuclear weapons require uranium enriched to at least 85-90% U-235.",
            "Depleted uranium is uranium that has had most of its U-235 removed. It is effectively pure U-238.",
            "In the 1920s, uranium was considered a useless byproduct of the production of radium.",
            "The Manhattan Project referred to refined natural uranium as tuballoy, enriched uranium as oralloy, and depleted uranium as depletalloy."
    };

    /** Original onItemRightClick: das Plutoniumpellet erzaehlt einen Fakt (gelb) mit Orb-Klang. */
    @Override
    public net.minecraft.world.InteractionResultHolder<ItemStack> use(Level world, net.minecraft.world.entity.player.Player player, net.minecraft.world.InteractionHand hand) {
        ItemStack stack = player.getItemInHand(hand);
        if (!world.isClientSide && this == ModItems.PELLET_RTG.get()) {
            player.sendSystemMessage(Component.literal(facts[world.random.nextInt(facts.length)]).withStyle(ChatFormatting.YELLOW));
            world.playSound(null, player.getX(), player.getY(), player.getZ(), net.minecraft.sounds.SoundEvents.EXPERIENCE_ORB_PICKUP, net.minecraft.sounds.SoundSource.PLAYERS, 1.0F, 1.0F);
        }
        return net.minecraft.world.InteractionResultHolder.pass(stack);
    }

    public short getHeat()       { return heat; }
    public long getMaxLifespan() { return lifespan; }
    public boolean doesDecay()   { return decayItem != null && lifespan > 0L; }

    @Nullable
    public ItemStack getDecayItem() {
        return decayItem == null ? null : new ItemStack(decayItem.get());
    }

    /** Original: {@code getLifespan} - ohne Marke gilt das Pellet als frisch. */
    public long getLifespan(ItemStack stack) {
        if (!(stack.getItem() instanceof ItemRTGPellet)) return 0L;

        if (stack.hasTag() && stack.getTag().contains(KEY_DEPLETION)) {
            return stack.getTag().getLong(KEY_DEPLETION);
        }

        stack.getOrCreateTag().putLong(KEY_DEPLETION, getMaxLifespan());
        return getMaxLifespan();
    }

    /** Original: {@code decay} - ein Tick weniger. */
    public void decay(ItemStack stack) {
        if (!doesDecay()) return;
        stack.getOrCreateTag().putLong(KEY_DEPLETION, getLifespan(stack) - 1L);
    }

    /** Original: {@code getScaledPower} - die Heizleistung sinkt mit der Restlaufzeit. */
    public static short getScaledPower(ItemRTGPellet fuel, ItemStack stack) {
        if (fuel.getMaxLifespan() <= 0L) return fuel.getHeat();
        return (short) Math.ceil(fuel.getHeat()
                * ((double) fuel.getLifespan(stack) / (double) fuel.getMaxLifespan()));
    }

    /** Original: {@code RTGUtil.getPower}. */
    public static short getPower(ItemRTGPellet fuel, ItemStack stack) {
        return com.hbm_m.config.VersatileConfig.scaleRTGPower() && fuel.doesDecay() ? getScaledPower(fuel, stack) : fuel.getHeat();
    }

    /**
     * Original: {@code handleDecay} - ist die Laufzeit herum, wird das Pellet zum Zerfallsprodukt,
     * sonst altert es um einen Tick.
     */
    public static ItemStack handleDecay(ItemStack stack, ItemRTGPellet pellet) {
        if (!pellet.doesDecay() || !com.hbm_m.config.VersatileConfig.rtgDecay()) return stack;

        if (pellet.getLifespan(stack) <= 0L) {
            ItemStack decayed = pellet.getDecayItem();
            return decayed == null ? ItemStack.EMPTY : decayed;
        }

        pellet.decay(stack);
        return stack;
    }

    // ── Die Sammelrechnung der Maschinen ────────────────────────────────────

    /** Original: {@code RTGUtil.hasHeat}. */
    public static boolean hasHeat(com.hbm_m.platform.ModItemStackHandler inventory, int[] slots) {
        for (int slot : slots) {
            if (inventory.getStackInSlot(slot).getItem() instanceof ItemRTGPellet) return true;
        }
        return false;
    }

    /**
     * 1:1-Port von {@code RTGUtil.updateRTGs}: die Summe der Heizleistung aller eingelegten
     * Pellets - und im selben Zug altert jedes von ihnen um einen Tick.
     */
    public static int updateRTGs(com.hbm_m.platform.ModItemStackHandler inventory, int[] slots) {
        int newHeat = 0;

        for (int slot : slots) {
            ItemStack stack = inventory.getStackInSlot(slot);
            if (!(stack.getItem() instanceof ItemRTGPellet pellet)) continue;

            newHeat += getPower(pellet, stack);
            inventory.setStackInSlot(slot, handleDecay(stack, pellet));
        }

        return newHeat;
    }

    // ── Kurzinfo ────────────────────────────────────────────────────────────

    //? if < 1.21.1 {
    @Override
    public void appendHoverText(ItemStack stack, @Nullable Level level, List<Component> tooltip, TooltipFlag flag) {
        addInfo(stack, tooltip, flag.isAdvanced());
    }
    //?} else {
    /*@Override
    public void appendHoverText(ItemStack stack, Item.TooltipContext context, List<Component> tooltip, TooltipFlag flag) {
        addInfo(stack, tooltip, flag.isAdvanced());
    }
    *///?}

    /** 1:1 {@code ItemRTGPellet.addInformation}: Beschreibung, Leistung, Zerfall, Restanteil, erweiterte Infos (F3+H). */
    private void addInfo(ItemStack stack, List<Component> tooltip, boolean ext) {
        tooltip.add(Component.translatable(this.getDescriptionId() + ".desc").withStyle(ChatFormatting.GRAY));
        tooltip.add(Component.translatable("desc.item.rtgHeat", getPower(this, stack)).withStyle(ChatFormatting.GRAY));

        if (!doesDecay()) return;

        ItemStack decayed = getDecayItem();
        if (decayed != null) {
            tooltip.add(Component.translatable("desc.item.rtgDecay", decayed.getHoverName(), decayed.getCount())
                    .withStyle(ChatFormatting.GRAY));
        }

        tooltip.add(Component.literal(com.hbm_m.util.BobMathUtil.toPercentage(getLifespan(stack), getMaxLifespan())).withStyle(ChatFormatting.GRAY));
        if (ext) {
            tooltip.add(Component.literal("EXTENDED INFO:").withStyle(ChatFormatting.GRAY));
            tooltip.add(Component.literal(String.format(java.util.Locale.US, "%s / %s ticks", getLifespan(stack), getMaxLifespan())).withStyle(ChatFormatting.GRAY));
            final String[] timeLeft = com.hbm_m.util.BobMathUtil.ticksToDate(getLifespan(stack));
            final String[] maxLife = com.hbm_m.util.BobMathUtil.ticksToDate(getMaxLifespan());
            tooltip.add(Component.literal(String.format(java.util.Locale.US, "Time remaining: %s y, %s d, %s h", (Object[]) timeLeft)).withStyle(ChatFormatting.GRAY));
            tooltip.add(Component.literal(String.format(java.util.Locale.US, "Maximum life: %s y, %s d, %s h", (Object[]) maxLife)).withStyle(ChatFormatting.GRAY));
        }
    }

    /** Original: {@code showDurabilityBar} - der Balken erscheint erst nach dem ersten Tick. */
    @Override
    public boolean isBarVisible(ItemStack stack) {
        return doesDecay() && getLifespan(stack) != getMaxLifespan();
    }

    @Override
    public int getBarWidth(ItemStack stack) {
        if (getMaxLifespan() <= 0L) return 13;
        return (int) Math.round(13.0D * getLifespan(stack) / getMaxLifespan());
    }

    @Override
    public int getBarColor(ItemStack stack) {
        return 0x4CC44C;
    }

    /** Damit {@link ModItems} die Zerfallsprodukte ohne Ringschluss anmelden kann. */
    public static Supplier<Item> depleted(Supplier<Item> item) {
        return item;
    }
}
