package com.hbm_m.config.schema;

import com.hbm_m.config.ClientConfig;
import com.hbm_m.config.GeneralConfig;
import com.hbm_m.config.MachineConfig;
import com.hbm_m.config.MobConfig;
import com.hbm_m.config.RadiationConfig;
import com.hbm_m.config.StructureConfig;
import com.hbm_m.config.WeaponConfig;
import com.hbm_m.config.WorldConfig;
import com.hbm_m.config.schema.ConfigField.FieldType;

import java.util.function.Consumer;

/**
 * Restport: Original-Konfigoptionen, deren Werte in den statischen Feldern der *Config-Klassen liegen
 * (Lesestellen bleiben {@code WorldConfig.uraniumSpawn} usw.). Standardwerte = Feldvorgaben = Original-loadFromConfig,
 * Kommentare 1:1 aus dem Original. Erzeugt von scratchpad/gen_cfg_fields.py - bei neuen Feldern dort nachziehen.
 */
final class RestportConfigFields {

    private RestportConfigFields() { }

    private static void s(Consumer<ConfigField> r, Class<?> owner, String key, FieldType type, ConfigSide side, ApplyMode mode,
                          String cat, Double min, Double max, String comment) {
        ConfigField.Builder b = ConfigField.builder(key, type).side(side).applyMode(mode).category(cat).staticIn(owner);
        if (min != null && max != null) b.range(min, max);
        r.accept(b.build().withComment(comment));
    }

    static void addTo(Consumer<ConfigField> r) {
        // ── GeneralConfig (1.xx, 528, LBSM) ──
        s(r, GeneralConfig.class, "enable528", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "528", null, null, "The central toggle for 528 mode, required TRUE for most subsequent toggles to work. [Original: enable528Mode]");
        s(r, GeneralConfig.class, "enableDebugMode", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "general", null, null, "Enable debugging mode [Original: 1.00_enableDebugMode]");
        s(r, GeneralConfig.class, "enablePlutoniumOre", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "general", null, null, "Enables plutonium ore generation in the nether [Original: 1.02_enablePlutoniumNetherOre]");
        s(r, GeneralConfig.class, "enableDungeons", FieldType.INT, ConfigSide.SERVER, ApplyMode.LIVE, "general", 0D, (double) 2, "Allows structures and dungeons to spawn. 0 = false, 1 = true, 2 = flag (respects the \"Generate Structures\" world flag). [Original: 1.03_enableDungeonSpawn]");
        s(r, GeneralConfig.class, "enableMDOres", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "general", null, null, "Allows NTM ores to generate in modded dimensions [Original: 1.04_enableOresInModdedDimensions]");
        s(r, GeneralConfig.class, "enableMines", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "general", null, null, "Allows landmines to generate [Original: 1.05_enableLandmineSpawn]");
        s(r, GeneralConfig.class, "enableRad", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "general", null, null, "Allows radiation hotspots to generate [Original: 1.06_enableRadHotspotSpawn]");
        s(r, GeneralConfig.class, "enableVaults", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "general", null, null, "Allows locked safes to spawn [Original: 1.15_enableVaultSpawn]");
        s(r, GeneralConfig.class, "enableCrosshairs", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "general", null, null, "Shows custom crosshairs when an NTM gun is being held [Original: 1.22_enableCrosshairs]");
        s(r, GeneralConfig.class, "enableSkyboxes", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "general", null, null, "If enabled, will try to use NTM's custom skyboxes. [Original: 1.31_enableSkyboxes]");
        s(r, GeneralConfig.class, "enableImpactWorldProvider", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "general", null, null, "If enabled, registers custom world provider which modifies lighting and sky colors for post impact effects. [Original: 1.32_enableImpactWorldProvider]");
        s(r, GeneralConfig.class, "enableGuideBook", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "general", null, null, "If enabled, gives players the guide book when joining the world for the first time [Original: 1.37_enableGuideBook]");
        s(r, GeneralConfig.class, "enableExpensiveMode", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "general", null, null, "It does what the name implies. [Original: 1.99_enableExpensiveMode]");
        s(r, GeneralConfig.class, "enable528ReasimBoilers", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "528", null, null, "Keeps the RBMK dial for ReaSim boilers on, preventing use of non-ReaSim boiler columns and forcing the use of steam in-/outlets [Original: X528_forceReasimBoilers]");
        s(r, GeneralConfig.class, "enable528BosniaSimulator", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "528", null, null, "Enables anti tank mines spawning all over the world. [Original: X528_enableBosniaSimulator]");
        s(r, GeneralConfig.class, "enable528PressurizedRecipes", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "528", null, null, "Sets some recipes to require pressurized input fluid [Original: X528_enable528PressurizedRecipes]");
        s(r, GeneralConfig.class, "enableLBSM", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "lbsm", null, null, "The central toggle for LBS mode. Forced OFF when 528 is enabled! [Original: enableLessBullshitMode]");
        s(r, GeneralConfig.class, "enableLBSMFullSchrab", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "lbsm", null, null, "When enabled, this will replace schraranium with full schrabidium ingots in the transmutator's output [Original: LBSM_fullSchrab]");
        s(r, GeneralConfig.class, "enableLBSMShorterDecay", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "lbsm", null, null, "When enabled, this will highly accelerate the speed at which nuclear waste disposal drums decay their contents. 60x faster than 528 mode and 5-12x faster than on normal mode. [Original: LBSM_shortDecay]");
        s(r, GeneralConfig.class, "enableLBSMSimpleArmorRecipes", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "lbsm", null, null, "When enabled, simplifies the recipe for armor sets like starmetal or schrabidium. [Original: LBSM_recipeSimpleArmor]");
        s(r, GeneralConfig.class, "enableLBSMSimpleToolRecipes", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "lbsm", null, null, "When enabled, simplifies the recipe for tool sets like starmetal or scrhabidium [Original: LBSM_recipeSimpleTool]");
        s(r, GeneralConfig.class, "enableLBSMSimpleAlloy", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "lbsm", null, null, "When enabled, adds some blast furnace recipes to make certain things cheaper [Original: LBSM_recipeSimpleAlloy]");
        s(r, GeneralConfig.class, "enableLBSMSimpleChemsitry", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "lbsm", null, null, "When enabled, simplifies some chemical plant recipes [Original: LBSM_recipeSimpleChemistry]");
        s(r, GeneralConfig.class, "enableLBSMSimpleCentrifuge", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "lbsm", null, null, "When enabled, enhances centrifuge outputs to make rare materials more common [Original: LBSM_recipeSimpleCentrifuge]");
        s(r, GeneralConfig.class, "enableLBSMUnlockAnvil", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "lbsm", null, null, "When enabled, all anvil recipes are available at tier 1 [Original: LBSM_recipeUnlockAnvil]");
        s(r, GeneralConfig.class, "enableLBSMSimpleCrafting", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "lbsm", null, null, "When enabled, some uncraftable or more expansive items get simple crafting recipes. Scorched uranium also becomes washable [Original: LBSM_recipeSimpleCrafting]");
        s(r, GeneralConfig.class, "enableLBSMSimpleMedicineRecipes", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "lbsm", null, null, "When enabled, makes some medicine recipes (like ones that require bismuth) much more affordable [Original: LBSM_recipeSimpleMedicine]");
        s(r, GeneralConfig.class, "enableLBSMSafeCrates", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "lbsm", null, null, "When enabled, prevents crates from becoming radioactive [Original: LBSM_safeCrates]");
        s(r, GeneralConfig.class, "schrabRate", FieldType.INT, ConfigSide.SERVER, ApplyMode.LIVE, "lbsm", 1D, (double) Integer.MAX_VALUE, "Changes the amount of uranium ore needed on average to create one schrabidium ore using nukes. Standard mode value is 100 [Original: LBSM_schrabOreRate]");
        // ── WorldConfig (2.xx Erze, 4.xx Dungeons) ──
        s(r, WorldConfig.class, "bedrockIronSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for iron bedrock ore [Original: 2.B00_bedrockIronWeight]");
        s(r, WorldConfig.class, "bedrockCopperSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for copper bedrock ore [Original: 2.B01_bedrockCopperWeight]");
        s(r, WorldConfig.class, "bedrockBoraxSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for borax bedrock ore [Original: 2.B02_bedrockBoraxWeight]");
        s(r, WorldConfig.class, "bedrockChlorocalciteSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for chlorocalcite bedrock ore [Original: 2.B14_bedrockChlorocalciteWeight]");
        s(r, WorldConfig.class, "bedrockAsbestosSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for asbestos bedrock ore [Original: 2.B03_bedrockAsbestosWeight]");
        s(r, WorldConfig.class, "bedrockNiobiumSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for niobium bedrock ore [Original: 2.B04_bedrockNiobiumWeight]");
        s(r, WorldConfig.class, "bedrockNeodymiumSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for neodymium bedrock ore [Original: 2.B15_bedrockNeodymiumWeight]");
        s(r, WorldConfig.class, "bedrockTitaniumSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for titanium bedrock ore [Original: 2.B05_bedrockTitaniumWeight]");
        s(r, WorldConfig.class, "bedrockTungstenSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for tungsten bedrock ore [Original: 2.B06_bedrockTungstenWeight]");
        s(r, WorldConfig.class, "bedrockGoldSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for gold bedrock ore [Original: 2.B07_bedrockGoldWeight]");
        s(r, WorldConfig.class, "bedrockUraniumSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for uranium bedrock ore [Original: 2.B08_bedrockUraniumWeight]");
        s(r, WorldConfig.class, "bedrockThoriumSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for thorium bedrock ore [Original: 2.B09_bedrockThoriumWeight]");
        s(r, WorldConfig.class, "bedrockCoalSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for coal bedrock ore [Original: 2.B10_bedrockCoalWeight]");
        s(r, WorldConfig.class, "bedrockNiterSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for niter bedrock ore [Original: 2.B11_bedrockNiterWeight]");
        s(r, WorldConfig.class, "bedrockFluoriteSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for fluorite bedrock ore [Original: 2.B12_bedrockFluoriteWeight]");
        s(r, WorldConfig.class, "bedrockRedstoneSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for redstone bedrock ore [Original: 2.B13_bedrockRedstoneWeight]");
        s(r, WorldConfig.class, "bedrockRareEarthSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for rare earth bedrock ore [Original: 2.B16_bedrockRareEarthWeight]");
        s(r, WorldConfig.class, "bedrockBauxiteSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for bauxite bedrock ore [Original: 2.B17_bedrockBauxiteWeight]");
        s(r, WorldConfig.class, "bedrockEmeraldSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for emerald bedrock ore [Original: 2.B18_bedrockEmeraldWeight]");
        s(r, WorldConfig.class, "bedrockGlowstoneSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for glowstone bedrock ore [Original: 2.BN00_bedrockGlowstoneWeight]");
        s(r, WorldConfig.class, "bedrockPhosphorusSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for phosphorus bedrock ore [Original: 2.BN01_bedrockPhosphorusWeight]");
        s(r, WorldConfig.class, "bedrockQuartzSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawn weight for quartz bedrock ore [Original: 2.BN01_bedrockQuartzWeight]");
        s(r, WorldConfig.class, "overworldOre", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", null, null, "General switch for whether overworld ores should be generated. Does not include special structures like oil. [Original: 2.D00_overworldOres]");
        s(r, WorldConfig.class, "netherOre", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", null, null, "General switch for whether nether ores should be generated. [Original: 2.D01_netherOres]");
        s(r, WorldConfig.class, "endOre", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", null, null, "General switch for whether end ores should be generated. Does not include special structures like trixite crystals. [Original: 2.D02_endOres]");
        s(r, WorldConfig.class, "uraniumSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of uranium ore veins per chunk [Original: 2.00_uraniumSpawnrate]");
        s(r, WorldConfig.class, "thoriumSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of thorium ore veins per chunk [Original: 2.10_thoriumSpawnrate]");
        s(r, WorldConfig.class, "titaniumSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of titanium ore veins per chunk [Original: 2.01_titaniumSpawnrate]");
        s(r, WorldConfig.class, "sulfurSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of sulfur ore veins per chunk [Original: 2.02_sulfurSpawnrate]");
        s(r, WorldConfig.class, "aluminiumSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of aluminium ore veins per chunk [Original: 2.03_aluminiumSpawnrate]");
        s(r, WorldConfig.class, "copperSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of copper ore veins per chunk [Original: 2.04_copperSpawnrate]");
        s(r, WorldConfig.class, "fluoriteSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of fluorite ore veins per chunk [Original: 2.05_fluoriteSpawnrate]");
        s(r, WorldConfig.class, "niterSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of niter ore veins per chunk [Original: 2.06_niterSpawnrate]");
        s(r, WorldConfig.class, "tungstenSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of tungsten ore veins per chunk [Original: 2.07_tungstenSpawnrate]");
        s(r, WorldConfig.class, "leadSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of lead ore veins per chunk [Original: 2.08_leadSpawnrate]");
        s(r, WorldConfig.class, "berylliumSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of beryllium ore veins per chunk [Original: 2.09_berylliumSpawnrate]");
        s(r, WorldConfig.class, "ligniteSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of lignite ore veins per chunk [Original: 2.11_ligniteSpawnrate]");
        s(r, WorldConfig.class, "asbestosSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of asbestos ore veins per chunk [Original: 2.12_asbestosSpawnRate]");
        s(r, WorldConfig.class, "rareSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of rare earth ore veins per chunk [Original: 2.14_rareEarthSpawnRate]");
        s(r, WorldConfig.class, "lithiumSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of schist lithium ore veins per chunk [Original: 2.13_lithiumSpawnRate]");
        s(r, WorldConfig.class, "cinnebarSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of cinnebar ore veins per chunk [Original: 2.18_cinnebarSpawnRate]");
        s(r, WorldConfig.class, "gassshaleSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of oil shale veins per chunk [Original: 2.16_gasShaleSpawnRate]");
        s(r, WorldConfig.class, "gasbubbleSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawns a gas bubble every nTH chunk [Original: 2.17_gasBubbleSpawnRate]");
        s(r, WorldConfig.class, "explosivebubbleSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawns an explosive gas bubble every nTH chunk [Original: 2.19_explosiveBubbleSpawnRate]");
        s(r, WorldConfig.class, "cobaltSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of cobalt ore veins per chunk [Original: 2.18_cobaltSpawnRate]");
        s(r, WorldConfig.class, "oilSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawns an oil bubble every nTH chunk [Original: 2.21_oilSpawnRate]");
        s(r, WorldConfig.class, "bedrockOilSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawns a bedrock oil node every nTH chunk [Original: 2.22_bedrockOilSpawnRate]");
        s(r, WorldConfig.class, "meteoriteSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawns a fallen meteorite every nTH chunk [Original: 2.23_meteoriteSpawnRate]");
        s(r, WorldConfig.class, "ironClusterSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of iron cluster veins per chunk [Original: 2.C00_ironClusterSpawn]");
        s(r, WorldConfig.class, "titaniumClusterSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of titanium cluster veins per chunk [Original: 2.C01_titaniumClusterSpawn]");
        s(r, WorldConfig.class, "aluminiumClusterSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of aluminium cluster veins per chunk [Original: 2.C02_aluminiumClusterSpawn]");
        s(r, WorldConfig.class, "copperClusterSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of copper cluster veins per chunk [Original: 2.C03_copperClusterSpawn]");
        s(r, WorldConfig.class, "alexandriteSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Spawns an alexandrite vein every nTH chunk [Original: 2.20_alexandriteSpawnRate]");
        s(r, WorldConfig.class, "limestoneSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of limestone block veins per chunk [Original: 2.L02_limestoneSpawn]");
        s(r, WorldConfig.class, "netherUraniumuSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of nether uranium per chunk [Original: 2.N00_uraniumSpawnrate]");
        s(r, WorldConfig.class, "netherTungstenSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of nether tungsten per chunk [Original: 2.N01_tungstenSpawnrate]");
        s(r, WorldConfig.class, "netherSulfurSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of nether sulfur per chunk [Original: 2.N02_sulfurSpawnrate]");
        s(r, WorldConfig.class, "netherPhosphorusSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of nether phosphorus per chunk [Original: 2.N03_phosphorusSpawnrate]");
        s(r, WorldConfig.class, "netherCoalSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of nether coal per chunk [Original: 2.N04_coalSpawnrate]");
        s(r, WorldConfig.class, "netherPlutoniumSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of nether plutonium per chunk, if enabled [Original: 2.N05_plutoniumSpawnrate]");
        s(r, WorldConfig.class, "netherCobaltSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of nether cobalt per chunk [Original: 2.N06_cobaltSpawnrate]");
        s(r, WorldConfig.class, "endTikiteSpawn", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", 0D, (double) Integer.MAX_VALUE, "Amount of end trixite per chunk [Original: 2.E00_tikiteSpawnrate]");
        s(r, WorldConfig.class, "enableHematite", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", null, null, "Toggles hematite deposits [Original: 2.L00_enableHematite]");
        s(r, WorldConfig.class, "enableMalachite", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", null, null, "Toggles malachite deposits [Original: 2.L01_enableMalachite]");
        s(r, WorldConfig.class, "enableBauxite", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", null, null, "Toggles bauxite deposits [Original: 2.L02_enableBauxite]");
        s(r, WorldConfig.class, "enableSulfurCave", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", null, null, "Toggles sulfur caves [Original: 2.C00_enableSulfurCave]");
        s(r, WorldConfig.class, "enableAsbestosCave", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "ores", null, null, "Toggles asbestos caves [Original: 2.C01_enableAsbestosCave]");
        s(r, WorldConfig.class, "antennaStructure", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn antenna on every nTH chunk [Original: 4.01_antennaSpawn]");
        s(r, WorldConfig.class, "atomStructure", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn power plant on every nTH chunk [Original: 4.02_atomSpawn]");
        s(r, WorldConfig.class, "dungeonStructure", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn library dungeon on every nTH chunk [Original: 4.04_dungeonSpawn]");
        s(r, WorldConfig.class, "satelliteStructure", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn satellite dish on every nTH chunk [Original: 4.06_satelliteSpawn]");
        s(r, WorldConfig.class, "dudStructure", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn dud on every nTH chunk [Original: 4.10_dudSpawn]");
        s(r, WorldConfig.class, "spaceshipStructure", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn spaceship on every nTH chunk [Original: 4.11_spaceshipSpawn]");
        s(r, WorldConfig.class, "barrelStructure", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn waste tank on every nTH chunk [Original: 4.12_barrelSpawn]");
        s(r, WorldConfig.class, "geyserChlorine", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn poison geyser on every nTH chunk [Original: 4.18_geyserChlorineSpawn]");
        s(r, WorldConfig.class, "geyserVapor", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn vapor geyser on every nTH chunk [Original: 4.19_geyserVaporSpawn]");
        s(r, WorldConfig.class, "arcticStructure", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn arctic code vault on every nTH chunk [Original: 4.22_arcticVaultSpawn]");
        s(r, WorldConfig.class, "jungleStructure", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn jungle dungeon on every nTH chunk [Original: 4.23_jungleDungeonSpawn]");
        s(r, WorldConfig.class, "pyramidStructure", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn pyramid on every nTH chunk [Original: 4.24_pyramidSpawn]");
        s(r, WorldConfig.class, "broadcaster", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn corrupt broadcaster on every nTH chunk [Original: 4.13_broadcasterSpawn]");
        s(r, WorldConfig.class, "minefreq", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn AP landmine on every nTH chunk [Original: 4.14_landmineSpawn]");
        s(r, WorldConfig.class, "radfreq", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn radiation hotspot on every nTH chunk [Original: 4.15_radHotspotSpawn]");
        s(r, WorldConfig.class, "vaultfreq", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "dungeons", 0D, (double) Integer.MAX_VALUE, "Spawn locked safe on every nTH chunk [Original: 4.16_vaultSpawn]");
        // ── StructureConfig (5.xx) ──
        s(r, StructureConfig.class, "enableStructures", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) 2, "Flag for whether modern NTM structures will spawn. 0 = false, 1 = true, 2 = flag (respects the \"Generate Structures\" world flag). [Original: 5.00_enableStructures]");
        s(r, StructureConfig.class, "structureMinChunks", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 1D, (double) Integer.MAX_VALUE, "Minimum non-zero distance between structures in chunks (Settings lower than 8 may be problematic). [Original: 5.01_structureMinChunks]");
        s(r, StructureConfig.class, "structureMaxChunks", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 1D, (double) Integer.MAX_VALUE, "Maximum non-zero distance between structures in chunks. [Original: 5.02_structureMaxChunks]");
        s(r, StructureConfig.class, "lootAmountFactor", FieldType.DOUBLE, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, 1000D, "General factor for loot spawns. Applies to spawned IInventories, not loot blocks. [Original: 5.03_lootAmountFactor]");
        s(r, StructureConfig.class, "debugStructures", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", null, null, "If enabled, special structure blocks like jigsaw blocks will not be transformed after generating [Original: 5.04_debugStructures]");
        s(r, StructureConfig.class, "enableRuins", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", null, null, "Toggle for all ruin structures (A through J) [Original: 5.05_enableRuins]");
        s(r, StructureConfig.class, "enableOceanStructures", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", null, null, "Toggle for ocean structures. (Aircraft carrier, oil rig, lighthouse.) [Original: 5.06_enableOceanStructures]");
        s(r, StructureConfig.class, "ruinsASpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for ruin A structure. [Original: 5.25_ruinASpawnWeight]");
        s(r, StructureConfig.class, "ruinsBSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for ruin B structure. [Original: 5.26_ruinBSpawnWeight]");
        s(r, StructureConfig.class, "ruinsCSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for ruin C structure. [Original: 5.27_ruinCSpawnWeight]");
        s(r, StructureConfig.class, "ruinsDSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for ruin D structure. [Original: 5.28_ruinDSpawnWeight]");
        s(r, StructureConfig.class, "ruinsESpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for ruin E structure. [Original: 5.29_ruinESpawnWeight]");
        s(r, StructureConfig.class, "ruinsFSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for ruin F structure. [Original: 5.30_ruinFSpawnWeight]");
        s(r, StructureConfig.class, "ruinsGSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for ruin G structure. [Original: 5.31_ruinGSpawnWeight]");
        s(r, StructureConfig.class, "ruinsHSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for ruin H structure. [Original: 5.32_ruinHSpawnWeight]");
        s(r, StructureConfig.class, "ruinsISpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for ruin I structure. [Original: 5.33_ruinISpawnWeight]");
        s(r, StructureConfig.class, "ruinsJSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for ruin J structure. [Original: 5.34_ruinJSpawnWeight]");
        s(r, StructureConfig.class, "plane1SpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for crashed plane 1 structure. [Original: 5.18_plane1SpawnWeight]");
        s(r, StructureConfig.class, "plane2SpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for crashed plane 2 structure. [Original: 5.19_plane2SpawnWeight]");
        s(r, StructureConfig.class, "desertShack1SpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for desert shack 1 structure. [Original: 5.20_desertShack1SpawnWeight]");
        s(r, StructureConfig.class, "desertShack2SpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for desert shack 2 structure. [Original: 5.21_desertShack2SpawnWeight]");
        s(r, StructureConfig.class, "desertShack3SpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for desert shack 3 structure. [Original: 5.22_desertShack3SpawnWeight]");
        s(r, StructureConfig.class, "laboratorySpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for laboratory structure/ [Original: 5.23_laboratorySpawnWeight]");
        s(r, StructureConfig.class, "lighthouseSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for lighthouse structure. [Original: 5.14_lighthouseSpawnWeight]");
        s(r, StructureConfig.class, "oilRigSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for oil rig structure. [Original: 5.13_oilRigSpawnWeight]");
        s(r, StructureConfig.class, "broadcastingTowerSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for broadcasting tower structure. [Original: 5.40_broadcastingTowerSpawnWeight]");
        s(r, StructureConfig.class, "waterPumpSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for water pump structure. [Original: 5.42_waterPumpSpawnWeight]");
        s(r, StructureConfig.class, "deadDishSmallSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for dead dish small structure. [Original: 5.43_deadDishSmallSpawnWeight]");
        s(r, StructureConfig.class, "beachedPatrolSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for beached patrol structure. [Original: 5.15_beachedPatrolSpawnWeight]");
        s(r, StructureConfig.class, "vertibirdSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for vertibird structure. [Original: 5.10_vertibirdSpawnWeight]");
        s(r, StructureConfig.class, "vertibirdCrashedSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for crashed vertibird structure. [Original: 5.11_crashedVertibirdSpawnWeight]");
        s(r, StructureConfig.class, "factorySpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for factory structure. [Original: 5.36_factorySpawnWeight]");
        s(r, StructureConfig.class, "radioSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for radio structure. [Original: 5.35_radioSpawnWeight]");
        s(r, StructureConfig.class, "forestChemSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for forest chemical plant structure. [Original: 5.17_forestChemSpawnWeight]");
        s(r, StructureConfig.class, "forestPostSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for forest post structure. [Original: 5.24_forestPostSpawnWeight]");
        s(r, StructureConfig.class, "towerBaseSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for tower base. [Original: 5.41_towerBaseSpawnWeight]");
        s(r, StructureConfig.class, "spireSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for spire structure. [Original: 5.07_spireSpawnWeight]");
        s(r, StructureConfig.class, "craneSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for crane structure. [Original: 5.39_craneSpawnWeight]");
        s(r, StructureConfig.class, "bunkerSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for bunker structure. [Original: 5.09_bunkerSpawnWeight]");
        s(r, StructureConfig.class, "dishSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for dish structures. [Original: 5.16_dishSpawnWeight]");
        s(r, StructureConfig.class, "featuresSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for misc structures (ex. Houses, offices.) [Original: 5.08_featuresSpawnWeight]");
        s(r, StructureConfig.class, "aircraftCarrierSpawnWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Spawn weight for aircraft carrier structure. [Original: 5.12_aircraftCarrierSpawnWeight]");
        s(r, StructureConfig.class, "plainsNullWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Null spawn weight for plains biome [Original: 5.37_plainsNullWeight]");
        s(r, StructureConfig.class, "oceanNullWeight", FieldType.INT, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "structures", 0D, (double) Integer.MAX_VALUE, "Null spawn weight for ocean biomes [Original: 5.38_oceanNullWeight]");
        // ── RadiationConfig (FOG, RADWORLD, HAZ, POL) ──
        s(r, RadiationConfig.class, "fogRad", FieldType.INT, ConfigSide.SERVER, ApplyMode.LIVE, "radiation", 0D, (double) Integer.MAX_VALUE, "Radiation in RADs required for fog to spawn [Original: FOG_00_threshold]");
        s(r, RadiationConfig.class, "fogCh", FieldType.INT, ConfigSide.SERVER, ApplyMode.LIVE, "radiation", 1D, (double) Integer.MAX_VALUE, "1:n chance of fog spawning every second [Original: FOG_01_threshold]");
        s(r, RadiationConfig.class, "worldRad", FieldType.INT, ConfigSide.SERVER, ApplyMode.LIVE, "radiation", 0D, (double) Integer.MAX_VALUE, "How many block operations radiation can perform per tick [Original: RADWORLD_01_amount]");
        s(r, RadiationConfig.class, "worldRadThreshold", FieldType.INT, ConfigSide.SERVER, ApplyMode.LIVE, "radiation", 0D, (double) Integer.MAX_VALUE, "The least amount of RADs required for block modification to happen [Original: RADWORLD_02_minimum]");
        s(r, RadiationConfig.class, "enableContamination", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "radiation", null, null, "Toggles player contamination (and negative effects from radiation poisoning) [Original: RADIATION_00_enableContamination]");
        s(r, RadiationConfig.class, "disableAsbestos", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "hazards", null, null, "When turned off, all asbestos hazards are disabled [Original: HAZ_00_disableAsbestos]");
        s(r, RadiationConfig.class, "disableCoal", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "hazards", null, null, "When turned off, all coal dust hazards are disabled [Original: HAZ_01_disableCoaldust]");
        s(r, RadiationConfig.class, "disableHot", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "hazards", null, null, "When turned off, all hot hazards are disabled [Original: HAZ_02_disableHot]");
        s(r, RadiationConfig.class, "disableExplosive", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "hazards", null, null, "When turned off, all explosive hazards are disabled [Original: HAZ_03_disableExplosive]");
        s(r, RadiationConfig.class, "disableHydro", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "hazards", null, null, "When turned off, all hydroactive hazards are disabled [Original: HAZ_04_disableHydroactive]");
        s(r, RadiationConfig.class, "disableBlinding", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "hazards", null, null, "When turned off, all blinding hazards are disabled [Original: HAZ_05_disableBlinding]");
        s(r, RadiationConfig.class, "disableFibrosis", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "hazards", null, null, "When turned off, all fibrosis hazards are disabled [Original: HAZ_06_disableFibrosis]");
        s(r, RadiationConfig.class, "enableSootFog", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "pollution", null, null, "Whether smog should be visible [Original: POL_03_enableSootFog]");
        s(r, RadiationConfig.class, "sootFogThreshold", FieldType.DOUBLE, ConfigSide.SERVER, ApplyMode.LIVE, "pollution", 0D, 1000000D, "How much soot is required for smog to become visible [Original: POL_06_sootFogThreshold]");
        s(r, RadiationConfig.class, "sootFogDivisor", FieldType.DOUBLE, ConfigSide.SERVER, ApplyMode.LIVE, "pollution", 0.001D, 1000000D, "The divisor for smog, higher numbers will require more soot for the same smog density [Original: POL_07_sootFogDivisor]");
        s(r, RadiationConfig.class, "smokeStackSootMult", FieldType.DOUBLE, ConfigSide.SERVER, ApplyMode.LIVE, "pollution", 0D, 1000000D, "How much does smokestack multiply soot by, with decimal values reducing the soot [Original: POL_08_smokeStackSootMult]");
        // ── MachineConfig (9.xx) ──
        s(r, MachineConfig.class, "scaleRTGPower", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "machines", null, null, "Should RTG/Betavoltaic fuel power scale down as it decays? [Original: 9.00_scaleRTGPower]");
        s(r, MachineConfig.class, "doRTGsDecay", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.REQUIRES_RESTART, "machines", null, null, "Should RTG/Betavoltaic fuel decay at all? [Original: 9.01_doRTGsDecay]");
        // ── MobConfig (12.Dxx) ──
        s(r, MobConfig.class, "enableDucks", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "mobs", null, null, "Whether pressing O should allow the player to duck [Original: 12.D00_enableDucks]");
        s(r, MobConfig.class, "enableMobGear", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "mobs", null, null, "Whether zombies and skeletons should have additional gear when spawning [Original: 12.D01_enableMobGear]");
        // ── WeaponConfig ──
        s(r, WeaponConfig.class, "ciwsHitrate", FieldType.INT, ConfigSide.SERVER, ApplyMode.LIVE, "weapons", 0D, (double) Integer.MAX_VALUE, "Additional modifier for CIWS accuracy [Original: 7.03_ciwsAccuracy]");
        s(r, WeaponConfig.class, "dropStar", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "weapons", null, null, "Whether rigged star blaster cells should explode when dropped [Original: 10.02_dropStar]");
        s(r, WeaponConfig.class, "linearAnimations", FieldType.BOOLEAN, ConfigSide.SERVER, ApplyMode.LIVE, "weapons", null, null, "Should heavily stylised weapon animations be replaced with more conventional ones? [Original: 18.00_linearAnimations]");
        // ── ClientConfig (hbmClient.json) ──
        s(r, ClientConfig.class, "geigerOffsetHorizontal", FieldType.INT, ConfigSide.CLIENT, ApplyMode.LIVE, "hud", -10000D, (double) 10000, "Horizontal offset of the geiger counter HUD [Original: GEIGER_OFFSET_HORIZONTAL]");
        s(r, ClientConfig.class, "geigerOffsetVertical", FieldType.INT, ConfigSide.CLIENT, ApplyMode.LIVE, "hud", -10000D, (double) 10000, "Vertical offset of the geiger counter HUD [Original: GEIGER_OFFSET_VERTICAL]");
        s(r, ClientConfig.class, "infoOffsetHorizontal", FieldType.INT, ConfigSide.CLIENT, ApplyMode.LIVE, "hud", -10000D, (double) 10000, "Horizontal offset of the info message box [Original: INFO_OFFSET_HORIZONTAL]");
        s(r, ClientConfig.class, "infoOffsetVertical", FieldType.INT, ConfigSide.CLIENT, ApplyMode.LIVE, "hud", -10000D, (double) 10000, "Vertical offset of the info message box [Original: INFO_OFFSET_VERTICAL]");
        s(r, ClientConfig.class, "infoPosition", FieldType.INT, ConfigSide.CLIENT, ApplyMode.LIVE, "hud", 0D, (double) 3, "Position of the info message box: 0 = top left, 1 = top right, 2 = right of crosshair, 3 = left of crosshair [Original: INFO_POSITION]");
        s(r, ClientConfig.class, "itemTooltipShowOredict", FieldType.BOOLEAN, ConfigSide.CLIENT, ApplyMode.LIVE, "hud", null, null, "Shows the item tags (ore dictionary names) in tooltips [Original: ITEM_TOOLTIP_SHOW_OREDICT]");
        s(r, ClientConfig.class, "itemTooltipShowCustomNuke", FieldType.BOOLEAN, ConfigSide.CLIENT, ApplyMode.LIVE, "hud", null, null, "Shows the custom nuke values in item tooltips [Original: ITEM_TOOLTIP_SHOW_CUSTOM_NUKE]");
        s(r, ClientConfig.class, "mainMenuWackySplashes", FieldType.BOOLEAN, ConfigSide.CLIENT, ApplyMode.LIVE, "hud", null, null, "Replaces main menu splashes with NTM ones [Original: MAIN_MENU_WACKY_SPLASHES]");
        s(r, ClientConfig.class, "doddRbmkDiagnostic", FieldType.BOOLEAN, ConfigSide.CLIENT, ApplyMode.LIVE, "hud", null, null, "Shows the RBMK diagnostic overlay when looking at RBMK parts [Original: DODD_RBMK_DIAGNOSTIC]");
        s(r, ClientConfig.class, "renderCableHang", FieldType.BOOLEAN, ConfigSide.CLIENT, ApplyMode.LIVE, "hud", null, null, "Renders pylon cables with sag [Original: RENDER_CABLE_HANG]");
        s(r, ClientConfig.class, "nukeHudFlash", FieldType.BOOLEAN, ConfigSide.CLIENT, ApplyMode.LIVE, "hud", null, null, "Nuclear explosions flash the screen [Original: NUKE_HUD_FLASH]");
        s(r, ClientConfig.class, "nukeHudShake", FieldType.BOOLEAN, ConfigSide.CLIENT, ApplyMode.LIVE, "hud", null, null, "Nuclear explosions shake the HUD [Original: NUKE_HUD_SHAKE]");
        s(r, ClientConfig.class, "coolingTowerParticles", FieldType.BOOLEAN, ConfigSide.CLIENT, ApplyMode.LIVE, "hud", null, null, "Cooling towers emit steam particles [Original: COOLING_TOWER_PARTICLES]");
        s(r, ClientConfig.class, "renderHeliostatBeamLimit", FieldType.INT, ConfigSide.CLIENT, ApplyMode.LIVE, "hud", 0D, (double) 100000, "How many heliostat beams a solar boiler may render [Original: RENDER_HELIOSTAT_BEAM_LIMIT]");
        s(r, ClientConfig.class, "badgesHud", FieldType.BOOLEAN, ConfigSide.CLIENT, ApplyMode.LIVE, "hud", null, null, "Shows the 528/expensive/rampant mode badges in the top left corner [Original: BADGES_HUD]");
    }
}
